// <auto-generated />
using System;
using IhtApcWebServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IhtApcWebServer.Migrations
{
    [DbContext(typeof(HardwareAPCDbContext))]
    partial class HardwareAPCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("SharedComponents.Models.ConstParamsInfo", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConstParam1")
                        .HasColumnType("REAL");

                    b.Property<double>("ConstParam2")
                        .HasColumnType("REAL");

                    b.Property<double>("ConstParam3")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ConstParams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7fb18342-6d7d-4a6b-90e0-ba3936592291"),
                            ConstParam1 = 1.0,
                            ConstParam2 = 1.0,
                            ConstParam3 = 1.0
                        },
                        new
                        {
                            Id = new Guid("d8126533-d7ec-4cad-94de-0472f4a6423c"),
                            ConstParam1 = 2.0,
                            ConstParam2 = 2.0,
                            ConstParam3 = 2.0
                        },
                        new
                        {
                            Id = new Guid("6cd18a28-8b9c-48fe-a7b8-c0e4d56c5328"),
                            ConstParam1 = 3.0,
                            ConstParam2 = 3.0,
                            ConstParam3 = 3.0
                        });
                });

            modelBuilder.Entity("SharedComponents.Models.DynamicParamsInfo", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("DynamicParam1")
                        .HasColumnType("REAL");

                    b.Property<double>("DynamicParam2")
                        .HasColumnType("REAL");

                    b.Property<double>("DynamicParam3")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DynamicParams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1bb6a3ce-5aca-4423-a98b-7834d44f6f28"),
                            DynamicParam1 = 1.0,
                            DynamicParam2 = 1.0,
                            DynamicParam3 = 1.0
                        },
                        new
                        {
                            Id = new Guid("094d2b09-8dff-4df8-8fbf-581e48d4d766"),
                            DynamicParam1 = 2.0,
                            DynamicParam2 = 2.0,
                            DynamicParam3 = 2.0
                        },
                        new
                        {
                            Id = new Guid("2f251f3d-0343-4bd6-bda9-019b5107c1df"),
                            DynamicParam1 = 3.0,
                            DynamicParam2 = 3.0,
                            DynamicParam3 = 3.0
                        });
                });

            modelBuilder.Entity("SharedComponents.Models.HardwareAPCModel", b =>
                {
                    b.Property<Guid?>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConstParamsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DynamicParamsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LiveParamsId")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("ConstParamsId");

                    b.HasIndex("DynamicParamsId");

                    b.HasIndex("LiveParamsId");

                    b.ToTable("HardwareAPCModel");

                    b.HasData(
                        new
                        {
                            DeviceId = new Guid("8ea36520-9bcf-4a0a-965b-9551fdfb2e81"),
                            ConstParamsId = new Guid("7fb18342-6d7d-4a6b-90e0-ba3936592291"),
                            DeviceName = "Device1",
                            DynamicParamsId = new Guid("1bb6a3ce-5aca-4423-a98b-7834d44f6f28"),
                            LiveParamsId = new Guid("ac695904-692f-4299-ae97-2988016b96a3")
                        },
                        new
                        {
                            DeviceId = new Guid("497d1dd6-e384-4017-baf9-0452c28493d5"),
                            ConstParamsId = new Guid("d8126533-d7ec-4cad-94de-0472f4a6423c"),
                            DeviceName = "Device2",
                            DynamicParamsId = new Guid("094d2b09-8dff-4df8-8fbf-581e48d4d766"),
                            LiveParamsId = new Guid("fc9dfc38-6ef6-4e18-9843-9e2facfc1da4")
                        },
                        new
                        {
                            DeviceId = new Guid("79392430-d2ab-4987-9914-04cd189298b5"),
                            ConstParamsId = new Guid("6cd18a28-8b9c-48fe-a7b8-c0e4d56c5328"),
                            DeviceName = "Device3",
                            DynamicParamsId = new Guid("2f251f3d-0343-4bd6-bda9-019b5107c1df"),
                            LiveParamsId = new Guid("ded9b16f-6f65-4871-9adc-568e1d16d669")
                        });
                });

            modelBuilder.Entity("SharedComponents.Models.LiveParamsInfo", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("LiveParam1")
                        .HasColumnType("REAL");

                    b.Property<double>("LiveParam2")
                        .HasColumnType("REAL");

                    b.Property<double>("LiveParam3")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LiveParams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac695904-692f-4299-ae97-2988016b96a3"),
                            LiveParam1 = 1.0,
                            LiveParam2 = 1.0,
                            LiveParam3 = 1.0
                        },
                        new
                        {
                            Id = new Guid("fc9dfc38-6ef6-4e18-9843-9e2facfc1da4"),
                            LiveParam1 = 2.0,
                            LiveParam2 = 2.0,
                            LiveParam3 = 2.0
                        },
                        new
                        {
                            Id = new Guid("ded9b16f-6f65-4871-9adc-568e1d16d669"),
                            LiveParam1 = 3.0,
                            LiveParam2 = 3.0,
                            LiveParam3 = 3.0
                        });
                });

            modelBuilder.Entity("SharedComponents.Models.HardwareAPCModel", b =>
                {
                    b.HasOne("SharedComponents.Models.ConstParamsInfo", "ConstParams")
                        .WithMany()
                        .HasForeignKey("ConstParamsId");

                    b.HasOne("SharedComponents.Models.DynamicParamsInfo", "DynamicParams")
                        .WithMany()
                        .HasForeignKey("DynamicParamsId");

                    b.HasOne("SharedComponents.Models.LiveParamsInfo", "LiveParams")
                        .WithMany()
                        .HasForeignKey("LiveParamsId");

                    b.Navigation("ConstParams");

                    b.Navigation("DynamicParams");

                    b.Navigation("LiveParams");
                });
#pragma warning restore 612, 618
        }
    }
}
