// <auto-generated />
using System;
using IhtApcWebServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IhtApcWebServer.Data.Migrations.APCHardware
{
    [DbContext(typeof(APCHardwareDBContext))]
    [Migration("20221205105856_Create_Schema_AndSeed2")]
    partial class Create_Schema_AndSeed2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.APCDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Num")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("APCDevices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4cf33-c1bb-49f7-bd78-e0139c26329d"),
                            Name = "APCDevice_1",
                            Num = 1
                        },
                        new
                        {
                            Id = new Guid("1e82c7d0-bc74-45dc-977e-11c446e8d9c7"),
                            Name = "APCDevice_2",
                            Num = 2
                        },
                        new
                        {
                            Id = new Guid("b45e6177-1c98-4067-96bf-8e193ef3af2b"),
                            Name = "APCDevice_3",
                            Num = 3
                        },
                        new
                        {
                            Id = new Guid("9b99b32e-2ae1-4d4e-bad2-e5d7303d82a2"),
                            Name = "APCDevice_4",
                            Num = 4
                        },
                        new
                        {
                            Id = new Guid("0e91a587-80cd-443b-9cc5-550987e021ae"),
                            Name = "APCDevice_5",
                            Num = 5
                        },
                        new
                        {
                            Id = new Guid("3d31b2b2-2a21-43f7-abc3-b748705d046c"),
                            Name = "APCDevice_6",
                            Num = 6
                        },
                        new
                        {
                            Id = new Guid("b3703fd8-116a-42e3-80aa-e26c641d3ce5"),
                            Name = "APCDevice_7",
                            Num = 7
                        },
                        new
                        {
                            Id = new Guid("88b6b637-69ef-448a-80e2-dcd5a9ee5bec"),
                            Name = "APCDevice_8",
                            Num = 8
                        },
                        new
                        {
                            Id = new Guid("27bf2a81-83eb-487e-a331-b553c1734829"),
                            Name = "APCDevice_9",
                            Num = 9
                        },
                        new
                        {
                            Id = new Guid("4062d96e-8dcf-4e6a-bfd2-c31cefc6bd30"),
                            Name = "APCDevice_10",
                            Num = 10
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ConstParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConstParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.DynParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ConstParamsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParameterDataInfoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConstParamsId");

                    b.HasIndex("ParameterDataInfoId");

                    b.ToTable("DynParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.LiveParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParameterDataInfoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParameterDataInfoId");

                    b.ToTable("LiveParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("APCDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DynParamsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("APCDeviceId");

                    b.HasIndex("DynParamsId");

                    b.ToTable("ParameterDatas");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinDescription")
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("StepDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParameterDataInfos");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParamSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParamType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamViewGroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParamViewGroupId");

                    b.ToTable("ParamSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98107d21-ce75-46d0-87b8-5c59bb38d3cb"),
                            ClientId = "default",
                            DisplayName = "Automatic Height Calibration",
                            Format = "",
                            ParamId = "TactileInitialPosFinding",
                            ParamName = "TactileInitialPosFinding",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("3e8c6962-d015-4e6a-9596-0aed6c3ec859"),
                            ClientId = "default",
                            DisplayName = "Manual Height Calibration",
                            Format = "",
                            ParamId = "DistanceCalibration",
                            ParamName = "DistanceCalibration",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("bd4f9433-71d4-4e7e-b96e-5b912c67a136"),
                            ClientId = "default",
                            DisplayName = "Position",
                            Format = "",
                            ParamId = "LinearDrivePosition",
                            ParamName = "LinearDrivePosition",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("4d03839d-bafc-4b5b-b7c8-c47857afc39e"),
                            ClientId = "default",
                            DisplayName = "Height Calibration Valid",
                            Format = "",
                            ParamId = "CalibrationValid",
                            ParamName = "IsCalibrationValid",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("6f1929ab-826e-4f9f-b791-fb3efc552d44"),
                            ClientId = "default",
                            DisplayName = "Height Calibration Active",
                            Format = "",
                            ParamId = "CalibrationActive",
                            ParamName = "IsCalibrationActive",
                            ParamOrder = 5,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("2f1e9425-a2d6-4424-9e0b-0073db63bc66"),
                            ClientId = "default",
                            DisplayName = "Retract Position",
                            Format = "",
                            ParamId = "RetractHeight",
                            ParamName = "RetractHeight",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("38570e3c-3323-4dee-ad7d-92d73bc0e015"),
                            ClientId = "default",
                            DisplayName = "Retract Position enable",
                            Format = "",
                            ParamId = "RetractPosAtProcessEnd",
                            ParamName = "IsRetractPosAtProcessEnd",
                            ParamOrder = 2,
                            ParamType = "SharedComponents.IhtData.DataCmdExecution",
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("a2ab2311-bcda-4f11-90f1-e55499c77dc5"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "SlagSensitivity",
                            ParamName = "Slag Sensitivity",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("41f76fd6-8903-48e6-98ea-91e5231dfe41"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "SlagPostTime",
                            ParamName = "Slag Post Time",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("78ddad54-cd2a-47c9-95ef-1bdff5463579"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "SlagCuttingSpeedReduction",
                            ParamName = "Slag Cutting Speed Reduction",
                            ParamOrder = 3,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 2
                        },
                        new
                        {
                            Id = new Guid("24c7f58f-cfb4-4bdb-8254-a8820fcf7342"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "CutO2Blowout",
                            ParamName = "Start Preflow",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("af74d2da-8db6-41a2-8332-bad99f28c781"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "CutO2BlowoutBreak",
                            ParamName = "Break Preflow",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("2a51ae39-1191-4861-b26f-ea93bc66db05"),
                            ClientId = "default",
                            DisplayName = "Preflow active",
                            Format = "",
                            ParamId = "CutO2BlowoutActive",
                            ParamName = "IsCutO2BlowoutActive",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("a0156951-bc10-4c97-a482-195363adcc82"),
                            ClientId = "default",
                            DisplayName = "Preflow active time",
                            Format = "",
                            ParamId = "CurrCutO2BlowoutTime",
                            ParamName = "CurrCutO2BlowoutTime",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("a320c3e1-2298-445f-8ac0-3808bd3b620f"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "CutO2BlowOutTime",
                            ParamName = "PreFlow Time",
                            ParamOrder = 5,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("2b36698b-c5bd-4bb3-bed1-847334cc70bf"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "CutO2BlowOutPressure",
                            ParamName = "PreFlow Pressure",
                            ParamOrder = 6,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("f72457be-aa05-4c37-af52-d4597f00ac16"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "CutO2BlowOutTimeOut",
                            ParamName = "PreFlow Timeout",
                            ParamOrder = 7,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("3b155c53-84e8-4223-8fd4-1d5b909b5197"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "HeightPierce",
                            ParamName = "Piercing with Height Control",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "Piercing",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("988d50e4-da71-460e-b9c8-53d7f58c436b"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "PiercingDetection",
                            ParamName = "Piercing detection",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "Piercing",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("10619308-db63-45d4-a490-7821aa81df32"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "Dynamic",
                            ParamName = "Dynamic",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("e6e3bea5-b23d-4ad8-bddb-589e998747a4"),
                            ClientId = "default",
                            DisplayName = "Height Control Active",
                            Format = "",
                            ParamId = "ClearanceCtrlOff",
                            ParamName = "IsHeightControlActive",
                            ParamOrder = 2,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("220b749b-1b3c-46b9-952f-8dfb27e359e4"),
                            ClientId = "default",
                            DisplayName = "",
                            Format = "",
                            ParamId = "LinearDrivePosition",
                            ParamName = "Position",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("a2c19306-5d10-46df-b4eb-e36ba241a7c1"),
                            ClientId = "default",
                            DisplayName = "Status Height Control",
                            Format = "{ 'Name':'Status Height Control', 'Mode':'Select', 'Values': ['Off','Low','Default','High'] }",
                            ParamId = "StatusHeightControl",
                            ParamName = "StatusHeightControl",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("ffc9f3df-8aea-4194-be45-3c5fc41ba9d9"),
                            ClientId = "client1",
                            DisplayName = "Automatic Height Calibration",
                            Format = "",
                            ParamId = "TactileInitialPosFinding",
                            ParamName = "TactileInitialPosFinding",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("8094597c-3d0f-4dda-a7bf-c68c917fd68a"),
                            ClientId = "client1",
                            DisplayName = "Manual Height Calibration",
                            Format = "",
                            ParamId = "DistanceCalibration",
                            ParamName = "DistanceCalibration",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("b3ed1735-7fe1-4c8d-9c3e-9d879a6f44c9"),
                            ClientId = "client1",
                            DisplayName = "Position",
                            Format = "",
                            ParamId = "LinearDrivePosition",
                            ParamName = "LinearDrivePosition",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("62b30c3c-bc25-41ac-9f85-091c11fcf869"),
                            ClientId = "client1",
                            DisplayName = "Height Calibration Valid",
                            Format = "",
                            ParamId = "CalibrationValid",
                            ParamName = "IsCalibrationValid",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("a8e4493b-103f-4bc6-835f-befa2385ab90"),
                            ClientId = "client1",
                            DisplayName = "Height Calibration Active",
                            Format = "",
                            ParamId = "CalibrationActive",
                            ParamName = "IsCalibrationActive",
                            ParamOrder = 5,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("ba3acd74-d1ae-48e4-9bbc-e9f7ea736180"),
                            ClientId = "client1",
                            DisplayName = "Retract Position",
                            Format = "",
                            ParamId = "RetractHeight",
                            ParamName = "RetractHeight",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("be24d791-1cec-4017-9fc5-7da1d90b6ebc"),
                            ClientId = "client1",
                            DisplayName = "Retract Position enable",
                            Format = "",
                            ParamId = "RetractPosAtProcessEnd",
                            ParamName = "IsRetractPosAtProcessEnd",
                            ParamOrder = 2,
                            ParamType = "SharedComponents.IhtData.DataCmdExecution",
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("46344d21-0a0e-4e50-b521-e06aefaa7873"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "SlagSensitivity",
                            ParamName = "Slag Sensitivity",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("8cbdc067-aa84-46e8-85f9-815d96201b0d"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "SlagPostTime",
                            ParamName = "Slag Post Time",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("0db6a864-02ee-443b-af45-df4b8a164167"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "SlagCuttingSpeedReduction",
                            ParamName = "Slag Cutting Speed Reduction",
                            ParamOrder = 3,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 2
                        },
                        new
                        {
                            Id = new Guid("a688c3db-57e1-4c18-8bfd-f24df64af5e8"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "CutO2Blowout",
                            ParamName = "Start Preflow",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("000eef62-74a0-41bf-ae86-d6d2d757afbd"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "CutO2BlowoutBreak",
                            ParamName = "Break Preflow",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("c25dd20d-5509-4086-a04c-9a7f2ca90d77"),
                            ClientId = "client1",
                            DisplayName = "Preflow active",
                            Format = "",
                            ParamId = "CutO2BlowoutActive",
                            ParamName = "IsCutO2BlowoutActive",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("449429eb-8514-4d3b-8c5c-04bd4e4f3409"),
                            ClientId = "client1",
                            DisplayName = "Preflow active time",
                            Format = "",
                            ParamId = "CurrCutO2BlowoutTime",
                            ParamName = "CurrCutO2BlowoutTime",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("18c66cbb-8274-41bc-976f-a236723b94e9"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "CutO2BlowOutTime",
                            ParamName = "PreFlow Time",
                            ParamOrder = 5,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("7145f9c6-db72-4627-a76a-be72a92a666b"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "CutO2BlowOutPressure",
                            ParamName = "PreFlow Pressure",
                            ParamOrder = 6,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("76fe1552-8ae6-48ec-8e37-86d2422fa84c"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "CutO2BlowOutTimeOut",
                            ParamName = "PreFlow Timeout",
                            ParamOrder = 7,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("1ddafcc6-2c3f-4bdb-8eb5-85b434ed9d93"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "HeightPierce",
                            ParamName = "Piercing with Height Control",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "Piercing",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("334d5d69-1188-457c-83ae-a87b185f81e0"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "PiercingDetection",
                            ParamName = "Piercing detection",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "Piercing",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("d9926fde-7458-4623-aa0f-0f5e23fba8ae"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "Dynamic",
                            ParamName = "Dynamic",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("d7b2c2eb-2e8e-4d6e-83de-709d66eae866"),
                            ClientId = "client1",
                            DisplayName = "Height Control Active",
                            Format = "",
                            ParamId = "ClearanceCtrlOff",
                            ParamName = "IsHeightControlActive",
                            ParamOrder = 2,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("cffc74db-3b62-478b-a7ec-73d9a907a4d2"),
                            ClientId = "client1",
                            DisplayName = "",
                            Format = "",
                            ParamId = "LinearDrivePosition",
                            ParamName = "Position",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("934be894-b253-466a-9482-e4696713f210"),
                            ClientId = "client1",
                            DisplayName = "Status Height Control",
                            Format = "{ 'Name':'Status Height Control', 'Mode':'Select', 'Values': ['Off','Low','Default','High'] }",
                            ParamId = "StatusHeightControl",
                            ParamName = "StatusHeightControl",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParamViewGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParamViewGroups");

                    b.HasData(
                        new
                        {
                            Id = "HeightCalibration",
                            GroupName = "Height Calibration",
                            GroupOrder = 1
                        },
                        new
                        {
                            Id = "RetractPosition",
                            GroupName = "Retract Position",
                            GroupOrder = 2
                        },
                        new
                        {
                            Id = "Slag",
                            GroupName = "Slag",
                            GroupOrder = 3
                        },
                        new
                        {
                            Id = "PreFlow",
                            GroupName = "Pre Flow",
                            GroupOrder = 4
                        },
                        new
                        {
                            Id = "Piercing",
                            GroupName = "Piercing",
                            GroupOrder = 5
                        },
                        new
                        {
                            Id = "HeightControl",
                            GroupName = "Height Control",
                            GroupOrder = 6
                        },
                        new
                        {
                            Id = "HeightCalibration_client1",
                            GroupName = "Height Calibration",
                            GroupOrder = 1
                        },
                        new
                        {
                            Id = "RetractPosition_client1",
                            GroupName = "Retract Position",
                            GroupOrder = 3
                        },
                        new
                        {
                            Id = "Slag_client1",
                            GroupName = "Slag",
                            GroupOrder = 2
                        },
                        new
                        {
                            Id = "PreFlow_client1",
                            GroupName = "Pre Flow",
                            GroupOrder = 4
                        },
                        new
                        {
                            Id = "Piercing_client1",
                            GroupName = "Piercing",
                            GroupOrder = 5
                        },
                        new
                        {
                            Id = "HeightControl_client1",
                            GroupName = "Height Control",
                            GroupOrder = 6
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.DynParams", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ConstParams", "ConstParams")
                        .WithMany("DynParams")
                        .HasForeignKey("ConstParamsId");

                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", "ParameterDataInfo")
                        .WithMany("DynParams")
                        .HasForeignKey("ParameterDataInfoId");

                    b.Navigation("ConstParams");

                    b.Navigation("ParameterDataInfo");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.LiveParams", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", "ParameterDataInfo")
                        .WithMany()
                        .HasForeignKey("ParameterDataInfoId");

                    b.Navigation("ParameterDataInfo");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterData", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.APCDevice", "APCDevice")
                        .WithMany("ParameterDatas")
                        .HasForeignKey("APCDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.DynParams", "DynParams")
                        .WithMany("ParameterDatas")
                        .HasForeignKey("DynParamsId");

                    b.Navigation("APCDevice");

                    b.Navigation("DynParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParamSettings", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ParamViewGroup", "ParamViewGroup")
                        .WithMany()
                        .HasForeignKey("ParamViewGroupId");

                    b.Navigation("ParamViewGroup");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.APCDevice", b =>
                {
                    b.Navigation("ParameterDatas");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ConstParams", b =>
                {
                    b.Navigation("DynParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.DynParams", b =>
                {
                    b.Navigation("ParameterDatas");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", b =>
                {
                    b.Navigation("DynParams");
                });
#pragma warning restore 612, 618
        }
    }
}
