// <auto-generated />
using System;
using IhtApcWebServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IhtApcWebServer.Data.Migrations.APCHardware
{
    [DbContext(typeof(APCHardwareDBContext))]
    partial class APCHardwareDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.APCDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Num")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("APCDevices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7215d1b-d13c-4ad8-9ae3-22e034c547ae"),
                            Name = "APCDevice_1",
                            Num = 1
                        },
                        new
                        {
                            Id = new Guid("e891bb40-93e8-4014-b53c-ceb73f3d84d6"),
                            Name = "APCDevice_2",
                            Num = 2
                        },
                        new
                        {
                            Id = new Guid("e7c63021-95c4-439e-9c62-42fe7081a9fc"),
                            Name = "APCDevice_3",
                            Num = 3
                        },
                        new
                        {
                            Id = new Guid("279c286c-a72b-49c8-befe-789c22700603"),
                            Name = "APCDevice_4",
                            Num = 4
                        },
                        new
                        {
                            Id = new Guid("b02308d0-01be-4a7a-b4fc-7fa01f6a3c50"),
                            Name = "APCDevice_5",
                            Num = 5
                        },
                        new
                        {
                            Id = new Guid("6aa188e1-d117-4ec8-87ef-be8c42274865"),
                            Name = "APCDevice_6",
                            Num = 6
                        },
                        new
                        {
                            Id = new Guid("1af10384-d68d-433f-9b05-cdb7f486493a"),
                            Name = "APCDevice_7",
                            Num = 7
                        },
                        new
                        {
                            Id = new Guid("b078bb1f-ade0-4559-884e-6ec5e31921a1"),
                            Name = "APCDevice_8",
                            Num = 8
                        },
                        new
                        {
                            Id = new Guid("559fa930-4305-4a54-80fb-9324ad369946"),
                            Name = "APCDevice_9",
                            Num = 9
                        },
                        new
                        {
                            Id = new Guid("93094d3c-f207-42ce-8c2a-f8b200bdaeed"),
                            Name = "APCDevice_10",
                            Num = 10
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ConstParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConstParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.DynParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ConstParamsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParameterDataInfoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConstParamsId");

                    b.HasIndex("ParameterDataInfoId");

                    b.ToTable("DynParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.LiveParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParameterDataInfoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParameterDataInfoId");

                    b.ToTable("LiveParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("APCDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DynParamsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("APCDeviceId");

                    b.HasIndex("DynParamsId");

                    b.ToTable("ParameterDatas");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinDescription")
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("StepDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParameterDataInfos");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParamSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParamType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamViewGroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParamViewGroupId");

                    b.ToTable("ParamSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("badc6839-4774-43e9-a5f7-13d8b735052e"),
                            ClientId = "default",
                            DisplayName = "Automatic Height Calibration",
                            Format = "{ 'Name':'Automatic Height Calibration', 'Mode':'Switch', 'Values': ['Disable', 'Enable'] }",
                            ParamId = "TactileInitialPosFinding",
                            ParamName = "TactileInitialPosFinding",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("f697e6ff-3e4c-4970-b892-7d4c503e6447"),
                            ClientId = "default",
                            DisplayName = "Manual Height Calibration",
                            Format = "{ 'Name':'Manual Height Calibration', 'Mode':'Slider', 'Unit' : true }",
                            ParamId = "DistanceCalibration",
                            ParamName = "DistanceCalibration",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("e5cee410-3551-4a9e-80d0-8d1b07c95c89"),
                            ClientId = "default",
                            DisplayName = "Position",
                            Format = "{ 'Unit' : true }",
                            ParamId = "LinearDrivePosition",
                            ParamName = "LinearDrivePosition",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("498e10d9-92a3-4df1-8392-ac266c543d5c"),
                            ClientId = "default",
                            DisplayName = "Height Calibration Valid",
                            Format = "{ 'Name':'Height Calibration Valid', 'Mode':'NoYes', 'Values':['No','Yes'],'ReadOnly':true }",
                            ParamId = "CalibrationValid",
                            ParamName = "IsCalibrationValid",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("b9d86967-8f50-4a2c-9bc5-e7e01c51b0c2"),
                            ClientId = "default",
                            DisplayName = "Height Calibration Active",
                            Format = "{ 'Name':'Height Calibration Valid', 'Mode':'NoYes', 'Values':['No','Yes'],'ReadOnly':true }",
                            ParamId = "CalibrationActive",
                            ParamName = "IsCalibrationActive",
                            ParamOrder = 5,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("f0a1d408-620e-4533-a659-b9d6dab0f37a"),
                            ClientId = "default",
                            DisplayName = "Retract Position",
                            Format = "{ 'Name':'Retract Position', 'Mode':'Slider' }",
                            ParamId = "RetractHeight",
                            ParamName = "RetractHeight",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("0dbf0724-5ae7-4dc8-934d-cbdee1c8eec7"),
                            ClientId = "default",
                            DisplayName = "Retract Position enable",
                            Format = "",
                            ParamId = "RetractPosAtProcessEnd",
                            ParamName = "IsRetractPosAtProcessEnd",
                            ParamOrder = 2,
                            ParamType = "SharedComponents.IhtData.DataCmdExecution",
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("a0d039c6-9d4c-466d-8e32-73041de16829"),
                            ClientId = "default",
                            DisplayName = "Slag Sensitivity",
                            Format = "{ 'Name':'Slag Sensitivity', 'Mode':'Select', 'Values': ['Off','Low','Default','High'] }",
                            ParamId = "SlagSensitivity",
                            ParamName = "SlagSensitivity",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("d3cee498-a8a2-419a-a99b-6174692ba678"),
                            ClientId = "default",
                            DisplayName = "Slag Post Time",
                            Format = "{ 'Name':'Slag Post Time', 'Mode':'Slider' }",
                            ParamId = "SlagPostTime",
                            ParamName = "SlagPostTime",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("96d5b4cd-5c37-4532-b875-db5c64c362d1"),
                            ClientId = "default",
                            DisplayName = "Slag Cutting Speed Reduction",
                            Format = "{ 'Name':'Slag Cutting Speed Reduction', 'Mode':'Slider' }",
                            ParamId = "SlagCuttingSpeedReduction",
                            ParamName = "SlagCuttingSpeedReduction",
                            ParamOrder = 3,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 2
                        },
                        new
                        {
                            Id = new Guid("162fd825-ebfd-4061-a932-a532c9435f43"),
                            ClientId = "default",
                            DisplayName = "Start Preflow",
                            Format = "{ 'Name':'Start Preflow', 'Mode':'NoYes', 'Values': ['No','Yes'] }",
                            ParamId = "CutO2Blowout",
                            ParamName = "CutO2Blowout",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("5ac0ac86-06dd-4c2a-81d3-1587516c2b88"),
                            ClientId = "default",
                            DisplayName = "Break Preflow",
                            Format = "",
                            ParamId = "CutO2BlowoutBreak",
                            ParamName = "CutO2BlowoutBreak",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("e4479e4b-67c0-4fb5-ba7b-d75c50cf5040"),
                            ClientId = "default",
                            DisplayName = "Preflow active",
                            Format = "",
                            ParamId = "CutO2BlowoutActive",
                            ParamName = "IsCutO2BlowoutActive",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("b1dc5880-ec74-4ee9-9d8c-74098a6d0657"),
                            ClientId = "default",
                            DisplayName = "Preflow active time",
                            Format = "",
                            ParamId = "CurrCutO2BlowoutTime",
                            ParamName = "CurrCutO2BlowoutTime",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("7de4ce8a-9db0-4189-9847-2bf9db8769b4"),
                            ClientId = "default",
                            DisplayName = "PreFlow Time",
                            Format = "{ 'Name':'PreFlow Time', 'Mode':'Slider' }",
                            ParamId = "CutO2BlowOutTime",
                            ParamName = "CutO2BlowOutTime",
                            ParamOrder = 5,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("5f12f4c3-ae36-4b15-868f-fdc35fa7456b"),
                            ClientId = "default",
                            DisplayName = "PreFlow Pressure",
                            Format = "{ 'Name':'PreFlow Pressure', 'Mode':'Slider' }",
                            ParamId = "CutO2BlowOutPressure",
                            ParamName = "CutO2BlowOutPressure",
                            ParamOrder = 6,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("2b3a4d6e-7e1d-4b5e-8682-389220b513b3"),
                            ClientId = "default",
                            DisplayName = "PreFlow Timeout",
                            Format = "{ 'Name':'PreFlow Timeout', 'Mode':'Slider' }",
                            ParamId = "CutO2BlowOutTimeOut",
                            ParamName = "CutO2BlowOutTimeOut",
                            ParamOrder = 7,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("3d6c4bba-a427-4193-a212-cb1ca71ab8f3"),
                            ClientId = "default",
                            DisplayName = "Piercing with Height Control",
                            Format = "",
                            ParamId = "PiercingSensorMode",
                            ParamName = "PiercingSensorMode",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "Piercing",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("d93c322c-d017-465e-8cd8-6bf567627c4a"),
                            ClientId = "default",
                            DisplayName = "Dynamic",
                            Format = "{ 'Name':'Dynamic', 'Mode':'Slider' }",
                            ParamId = "Dynamic",
                            ParamName = "Dynamic",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("a15fdfbf-fb87-4937-b979-46e1ed82ed0a"),
                            ClientId = "default",
                            DisplayName = "Height Control Active",
                            Format = "{ 'Name':'Height Control Active', 'Mode':'NoYes', 'Values': ['No','Yes'] }",
                            ParamId = "ClearanceCtrlOff",
                            ParamName = "IsHeightControlActive",
                            ParamOrder = 2,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("1618b4e0-5b8d-4348-a2f5-06b4a63949f4"),
                            ClientId = "default",
                            DisplayName = "Position",
                            Format = "{ 'Unit' : true }",
                            ParamId = "LinearDrivePosition",
                            ParamName = "LinearDrivePosition",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("12beab6d-04f8-424d-964f-4de7b08c1822"),
                            ClientId = "default",
                            DisplayName = "Status Height Control",
                            Format = "{ 'Name':'Status Height Control', 'Mode':'Select', 'Values': ['Off','PreHeating','Piercing','Cutting'] }",
                            ParamId = "StatusHeightControl",
                            ParamName = "StatusHeightControl",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("ab42d8d6-f752-435b-99f1-4fc32f5b02ae"),
                            ClientId = "client1",
                            DisplayName = "Automatic Height Calibration",
                            Format = "{ 'Name':'Automatic Height Calibration', 'Mode':'Switch', 'Values': ['Disable', 'Enable'] }",
                            ParamId = "TactileInitialPosFinding",
                            ParamName = "TactileInitialPosFinding",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("84ce1ec1-9f40-4d9a-973c-ded7a1941d43"),
                            ClientId = "client1",
                            DisplayName = "Manual Height Calibration",
                            Format = "{ 'Name':'Manual Height Calibration', 'Mode':'Slider', 'Unit' : true }",
                            ParamId = "DistanceCalibration",
                            ParamName = "DistanceCalibration",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("cc7592a8-2ee6-4fd7-b84d-0c3d2f7afe82"),
                            ClientId = "client1",
                            DisplayName = "Position",
                            Format = "{ 'Unit' : true }",
                            ParamId = "LinearDrivePosition",
                            ParamName = "LinearDrivePosition",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("13958bad-03ea-4c1f-bc3c-e0392302c97d"),
                            ClientId = "client1",
                            DisplayName = "Height Calibration Valid",
                            Format = "{ 'Name':'Height Calibration Valid', 'Mode':'NoYes', 'Values':['No','Yes'],'ReadOnly':true }",
                            ParamId = "CalibrationValid",
                            ParamName = "IsCalibrationValid",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("61c52adc-aaaa-4335-8591-8180f495ab33"),
                            ClientId = "client1",
                            DisplayName = "Height Calibration Active",
                            Format = "{ 'Name':'Height Calibration Valid', 'Mode':'NoYes', 'Values':['No','Yes'],'ReadOnly':true }",
                            ParamId = "CalibrationActive",
                            ParamName = "IsCalibrationActive",
                            ParamOrder = 5,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("0367b4ad-0876-48cb-90d2-281b4e3c9ceb"),
                            ClientId = "client1",
                            DisplayName = "Retract Position",
                            Format = "{ 'Name':'Retract Position', 'Mode':'Slider' }",
                            ParamId = "RetractHeight",
                            ParamName = "RetractHeight",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("5ab417cd-2d15-46b6-bfb7-e11012f4a7e0"),
                            ClientId = "client1",
                            DisplayName = "Retract Position enable",
                            Format = "",
                            ParamId = "RetractPosAtProcessEnd",
                            ParamName = "IsRetractPosAtProcessEnd",
                            ParamOrder = 2,
                            ParamType = "SharedComponents.IhtData.DataCmdExecution",
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("308c47f6-3be6-4926-ba68-9ba2957d143c"),
                            ClientId = "client1",
                            DisplayName = "Slag Sensitivity",
                            Format = "{ 'Name':'Slag Sensitivity', 'Mode':'Select', 'Values': ['Off','Low','Default','High'] }",
                            ParamId = "SlagSensitivity",
                            ParamName = "SlagSensitivity",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("5f29ffac-4833-40a4-a0ce-e12c9aa526b3"),
                            ClientId = "client1",
                            DisplayName = "Slag Post Time",
                            Format = "{ 'Name':'Slag Post Time', 'Mode':'Slider' }",
                            ParamId = "SlagPostTime",
                            ParamName = "SlagPostTime",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("2d285458-7abd-4d9f-bfca-52e5338c1556"),
                            ClientId = "client1",
                            DisplayName = "Slag Cutting Speed Reduction",
                            Format = "{ 'Name':'Slag Cutting Speed Reduction', 'Mode':'Slider' }",
                            ParamId = "SlagCuttingSpeedReduction",
                            ParamName = "SlagCuttingSpeedReduction",
                            ParamOrder = 3,
                            ParamType = "",
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 2
                        },
                        new
                        {
                            Id = new Guid("19c73840-fa97-4fe7-b114-dcba2c1efd08"),
                            ClientId = "client1",
                            DisplayName = "Start Preflow",
                            Format = "{ 'Name':'Start Preflow', 'Mode':'NoYes', 'Values': ['No','Yes'] }",
                            ParamId = "CutO2Blowout",
                            ParamName = "CutO2Blowout",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("b4570ff6-a110-49b4-944c-dc95036bc881"),
                            ClientId = "client1",
                            DisplayName = "Break Preflow",
                            Format = "",
                            ParamId = "CutO2BlowoutBreak",
                            ParamName = "CutO2BlowoutBreak",
                            ParamOrder = 2,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("5bc6b834-f959-4637-8e7f-f26185d4ee50"),
                            ClientId = "client1",
                            DisplayName = "Preflow active",
                            Format = "",
                            ParamId = "CutO2BlowoutActive",
                            ParamName = "IsCutO2BlowoutActive",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("fc0c00ad-61ef-4981-aa61-edf5f3aafda9"),
                            ClientId = "client1",
                            DisplayName = "Preflow active time",
                            Format = "",
                            ParamId = "CurrCutO2BlowoutTime",
                            ParamName = "CurrCutO2BlowoutTime",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("6fc1a888-af62-416c-a2b7-f12cb204bb5b"),
                            ClientId = "client1",
                            DisplayName = "PreFlow Time",
                            Format = "{ 'Name':'PreFlow Time', 'Mode':'Slider' }",
                            ParamId = "CutO2BlowOutTime",
                            ParamName = "CutO2BlowOutTime",
                            ParamOrder = 5,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("b4851fcd-a30c-4011-927d-5ec1749e4d33"),
                            ClientId = "client1",
                            DisplayName = "PreFlow Pressure",
                            Format = "{ 'Name':'PreFlow Pressure', 'Mode':'Slider' }",
                            ParamId = "CutO2BlowOutPressure",
                            ParamName = "CutO2BlowOutPressure",
                            ParamOrder = 6,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("d89d0e22-78d1-413a-b04e-c5924a5e85cf"),
                            ClientId = "client1",
                            DisplayName = "PreFlow Timeout",
                            Format = "{ 'Name':'PreFlow Timeout', 'Mode':'Slider' }",
                            ParamId = "CutO2BlowOutTimeOut",
                            ParamName = "CutO2BlowOutTimeOut",
                            ParamOrder = 7,
                            ParamType = "",
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("5e72f5af-5047-4bfc-b962-1f093253c15a"),
                            ClientId = "client1",
                            DisplayName = "Piercing with Height Control",
                            Format = "",
                            ParamId = "PiercingSensorMode",
                            ParamName = "PiercingSensorMode",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "Piercing",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("6c3af5ec-95ff-45ef-bc4a-16d4088634ad"),
                            ClientId = "client1",
                            DisplayName = "Dynamic",
                            Format = "{ 'Name':'Dynamic', 'Mode':'Slider' }",
                            ParamId = "Dynamic",
                            ParamName = "Dynamic",
                            ParamOrder = 1,
                            ParamType = "",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("a936744a-64ec-4bb5-ba1a-16c9f79f5219"),
                            ClientId = "client1",
                            DisplayName = "Height Control Active",
                            Format = "{ 'Name':'Height Control Active', 'Mode':'NoYes', 'Values': ['No','Yes'] }",
                            ParamId = "ClearanceCtrlOff",
                            ParamName = "IsHeightControlActive",
                            ParamOrder = 2,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("6f608bb2-c946-409c-883d-922bdd8fc474"),
                            ClientId = "client1",
                            DisplayName = "Position",
                            Format = "{ 'Unit' : true }",
                            ParamId = "LinearDrivePosition",
                            ParamName = "LinearDrivePosition",
                            ParamOrder = 3,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("50ccda05-c035-4538-becf-883e1c78852e"),
                            ClientId = "client1",
                            DisplayName = "Status Height Control",
                            Format = "{ 'Name':'Status Height Control', 'Mode':'Select', 'Values': ['Off','PreHeating','Piercing','Cutting'] }",
                            ParamId = "StatusHeightControl",
                            ParamName = "StatusHeightControl",
                            ParamOrder = 4,
                            ParamType = "SharedComponents.IhtData.DataProcessInfo",
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParamViewGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParamViewGroups");

                    b.HasData(
                        new
                        {
                            Id = "HeightCalibration",
                            GroupName = "Height Calibration",
                            GroupOrder = 1
                        },
                        new
                        {
                            Id = "RetractPosition",
                            GroupName = "Retract Position",
                            GroupOrder = 2
                        },
                        new
                        {
                            Id = "Slag",
                            GroupName = "Slag",
                            GroupOrder = 3
                        },
                        new
                        {
                            Id = "PreFlow",
                            GroupName = "Pre Flow",
                            GroupOrder = 4
                        },
                        new
                        {
                            Id = "Piercing",
                            GroupName = "Piercing",
                            GroupOrder = 5
                        },
                        new
                        {
                            Id = "HeightControl",
                            GroupName = "Height Control",
                            GroupOrder = 6
                        },
                        new
                        {
                            Id = "HeightCalibration_client1",
                            GroupName = "Height Calibration",
                            GroupOrder = 1
                        },
                        new
                        {
                            Id = "RetractPosition_client1",
                            GroupName = "Retract Position",
                            GroupOrder = 3
                        },
                        new
                        {
                            Id = "Slag_client1",
                            GroupName = "Slag",
                            GroupOrder = 2
                        },
                        new
                        {
                            Id = "PreFlow_client1",
                            GroupName = "Pre Flow",
                            GroupOrder = 4
                        },
                        new
                        {
                            Id = "Piercing_client1",
                            GroupName = "Piercing",
                            GroupOrder = 5
                        },
                        new
                        {
                            Id = "HeightControl_client1",
                            GroupName = "Height Control",
                            GroupOrder = 6
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.DynParams", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ConstParams", "ConstParams")
                        .WithMany("DynParams")
                        .HasForeignKey("ConstParamsId");

                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", "ParameterDataInfo")
                        .WithMany("DynParams")
                        .HasForeignKey("ParameterDataInfoId");

                    b.Navigation("ConstParams");

                    b.Navigation("ParameterDataInfo");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.LiveParams", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", "ParameterDataInfo")
                        .WithMany()
                        .HasForeignKey("ParameterDataInfoId");

                    b.Navigation("ParameterDataInfo");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterData", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.APCDevice", "APCDevice")
                        .WithMany("ParameterDatas")
                        .HasForeignKey("APCDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.DynParams", "DynParams")
                        .WithMany("ParameterDatas")
                        .HasForeignKey("DynParamsId");

                    b.Navigation("APCDevice");

                    b.Navigation("DynParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParamSettings", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ParamViewGroup", "ParamViewGroup")
                        .WithMany()
                        .HasForeignKey("ParamViewGroupId");

                    b.Navigation("ParamViewGroup");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.APCDevice", b =>
                {
                    b.Navigation("ParameterDatas");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ConstParams", b =>
                {
                    b.Navigation("DynParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.DynParams", b =>
                {
                    b.Navigation("ParameterDatas");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", b =>
                {
                    b.Navigation("DynParams");
                });
#pragma warning restore 612, 618
        }
    }
}
