// <auto-generated />
using System;
using IhtApcWebServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IhtApcWebServer.Data.Migrations.APCHardware
{
    [DbContext(typeof(APCHardwareDBContext))]
    partial class APCHardwareDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.APCDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Num")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("APCDevices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c22a835a-3dba-4ba5-ae52-e9ef27548c0c"),
                            Name = "APCDevice_1",
                            Num = 1
                        },
                        new
                        {
                            Id = new Guid("2ae7e626-1575-4c87-8e0d-2d5434da0687"),
                            Name = "APCDevice_2",
                            Num = 2
                        },
                        new
                        {
                            Id = new Guid("29cd85aa-c94d-44b3-ad78-41d3615fe092"),
                            Name = "APCDevice_3",
                            Num = 3
                        },
                        new
                        {
                            Id = new Guid("c0a3cc50-c28d-4548-ad16-d88b632722f2"),
                            Name = "APCDevice_4",
                            Num = 4
                        },
                        new
                        {
                            Id = new Guid("cd96bdb6-a49c-41d6-9d3e-75e7c6ffc32d"),
                            Name = "APCDevice_5",
                            Num = 5
                        },
                        new
                        {
                            Id = new Guid("dc6b6981-4a33-4518-8c7a-8dced1a1b527"),
                            Name = "APCDevice_6",
                            Num = 6
                        },
                        new
                        {
                            Id = new Guid("f8ac0435-1338-4e10-9b1f-ce7a0d3068ee"),
                            Name = "APCDevice_7",
                            Num = 7
                        },
                        new
                        {
                            Id = new Guid("c496f802-defb-4603-9837-6c25ede93d30"),
                            Name = "APCDevice_8",
                            Num = 8
                        },
                        new
                        {
                            Id = new Guid("740504cd-bb12-49ac-aab1-4f0703663958"),
                            Name = "APCDevice_9",
                            Num = 9
                        },
                        new
                        {
                            Id = new Guid("97f891c3-c4ea-4f05-b334-e4309c8f02b3"),
                            Name = "APCDevice_10",
                            Num = 10
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ConstParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConstParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.DynParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ConstParamsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParameterDataInfoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConstParamsId");

                    b.HasIndex("ParameterDataInfoId");

                    b.ToTable("DynParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.LiveParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParameterDataInfoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParameterDataInfoId");

                    b.ToTable("LiveParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("APCDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DynParamsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("APCDeviceId");

                    b.HasIndex("DynParamsId");

                    b.ToTable("ParameterDatas");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinDescription")
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("StepDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParameterDataInfos");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParamSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParamViewGroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParamViewGroupId");

                    b.ToTable("ParamSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6784375a-c4c0-4378-b7dd-4bc51faba4b5"),
                            ClientId = "default",
                            ParamId = "TactileInitialPosFinding",
                            ParamName = "Automatic Height Calibration",
                            ParamOrder = 1,
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("e02463f1-ad03-4ffe-94c8-9ec381809bdd"),
                            ClientId = "default",
                            ParamId = "DistanceCalibration",
                            ParamName = "Manual Height Calibration",
                            ParamOrder = 2,
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("08300fc0-cad4-4d17-99f5-de5e1c504a1d"),
                            ClientId = "default",
                            ParamId = "LinearDrivePosition",
                            ParamName = "Position",
                            ParamOrder = 3,
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("3fca3b41-4110-4635-8472-22d764d3a8a4"),
                            ClientId = "default",
                            ParamId = "CalibrationValid",
                            ParamName = "Height Calibration Valid",
                            ParamOrder = 4,
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("b3225e2d-fd79-4ef8-b770-bd95c0bf1c08"),
                            ClientId = "default",
                            ParamId = "CalibrationActive",
                            ParamName = "Height Calibration Active",
                            ParamOrder = 5,
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("10d63731-3f9b-47f6-962b-e256a39e9588"),
                            ClientId = "default",
                            ParamId = "RetractHeight",
                            ParamName = "Retract Position",
                            ParamOrder = 1,
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("4c1a6e1b-9ae8-4d65-8ef0-ff17d503f58d"),
                            ClientId = "default",
                            ParamId = "RetractPosAtProcessEnd",
                            ParamName = "Retract Position Enable",
                            ParamOrder = 2,
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("c8826180-77ea-452f-ab6b-5015bfdfc6fb"),
                            ClientId = "default",
                            ParamId = "SlagSensitivity",
                            ParamName = "Slag Sensitivity",
                            ParamOrder = 1,
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("9dd468bf-90c3-4ebb-a8a2-84245106a9a6"),
                            ClientId = "default",
                            ParamId = "SlagPostTime",
                            ParamName = "Slag Post Time",
                            ParamOrder = 2,
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("85059407-2db9-425b-b81b-73d44a4ee0b4"),
                            ClientId = "default",
                            ParamId = "SlagCuttingSpeedReduction",
                            ParamName = "Slag Cutting Speed Reduction",
                            ParamOrder = 3,
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 2
                        },
                        new
                        {
                            Id = new Guid("06b24411-1563-451d-82ba-71eec4e812ea"),
                            ClientId = "default",
                            ParamId = "CutO2Blowout",
                            ParamName = "Start Preflow",
                            ParamOrder = 1,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("81b8f4cc-b234-47f6-ab97-b0a2275713f2"),
                            ClientId = "default",
                            ParamId = "CutO2BlowoutBreak",
                            ParamName = "Break Preflow",
                            ParamOrder = 2,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("8ddfe0c7-b4be-4646-8a24-8fee7ea56852"),
                            ClientId = "default",
                            ParamId = "CutO2BlowoutActive",
                            ParamName = "Preflow active",
                            ParamOrder = 3,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("a6003575-9178-4ab9-9e4b-9e7d1aea050e"),
                            ClientId = "default",
                            ParamId = "CurrCutO2BlowoutTime",
                            ParamName = "Preflow active time",
                            ParamOrder = 4,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("29bf0b2a-784d-4459-91c7-61643e16620c"),
                            ClientId = "default",
                            ParamId = "CutO2BlowOutTime",
                            ParamName = "PreFlow Time",
                            ParamOrder = 5,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("57584ddd-57ee-4c67-92ab-821f58bdf9e1"),
                            ClientId = "default",
                            ParamId = "CutO2BlowOutPressure",
                            ParamName = "PreFlow Pressure",
                            ParamOrder = 6,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("579445b8-5132-4e8e-87dc-80e36c424fe0"),
                            ClientId = "default",
                            ParamId = "CutO2BlowOutTimeOut",
                            ParamName = "PreFlow Timeout",
                            ParamOrder = 7,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("03063d5f-c92b-4556-8783-19aa85c7ed01"),
                            ClientId = "default",
                            ParamId = "HeightPierce",
                            ParamName = "Piercing with Height Control",
                            ParamOrder = 1,
                            ParamViewGroupId = "Piercing",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("c7cd06ed-266e-4a5c-bc1b-916ce63b822c"),
                            ClientId = "default",
                            ParamId = "PiercingDetection",
                            ParamName = "Piercing detection",
                            ParamOrder = 2,
                            ParamViewGroupId = "Piercing",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("de7ac0aa-b451-4a0f-98fa-a1335eeaa3c5"),
                            ClientId = "default",
                            ParamId = "Dynamic",
                            ParamName = "Dynamic",
                            ParamOrder = 1,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("09f8881a-c38a-4c24-b016-64e15d31484f"),
                            ClientId = "default",
                            ParamId = "ClearanceCtrlOff",
                            ParamName = "Height Control Active",
                            ParamOrder = 2,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("a24bbd3c-c235-4893-bf8f-6c78924cab2a"),
                            ClientId = "default",
                            ParamId = "LinearDrivePosition",
                            ParamName = "Position",
                            ParamOrder = 3,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("a2ef24e9-2901-4bbb-95a2-c4544ae914fd"),
                            ClientId = "default",
                            ParamId = "Off",
                            ParamName = "Off",
                            ParamOrder = 4,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("ce158e16-db35-445a-a494-7b6b186b5721"),
                            ClientId = "default",
                            ParamId = "HeightPreHeat",
                            ParamName = "Preheating",
                            ParamOrder = 5,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("9692e2a6-a027-4a33-bece-71307283d762"),
                            ClientId = "default",
                            ParamId = "HeightPierce",
                            ParamName = "Piercing",
                            ParamOrder = 6,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("90fc142a-a2b2-43e2-9f9f-bec27560bcf0"),
                            ClientId = "default",
                            ParamId = "HeightCut",
                            ParamName = "Cutting",
                            ParamOrder = 7,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("035aaed8-d15a-4e26-9344-8dd1e9fb3c1b"),
                            ClientId = "client1",
                            ParamId = "TactileInitialPosFinding",
                            ParamName = "Automatic Height Calibration",
                            ParamOrder = 1,
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("f18cbdc5-b2ab-4671-8bc8-25a5eb129f46"),
                            ClientId = "client1",
                            ParamId = "DistanceCalibration",
                            ParamName = "Manual Height Calibration",
                            ParamOrder = 2,
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("7a51f64b-66d3-4dfe-98a3-811042c60a80"),
                            ClientId = "client1",
                            ParamId = "LinearDrivePosition",
                            ParamName = "Position",
                            ParamOrder = 3,
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("663f9a7d-1d20-4852-910b-63e265070731"),
                            ClientId = "client1",
                            ParamId = "CalibrationValid",
                            ParamName = "Height Calibration Valid",
                            ParamOrder = 4,
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("3f5ea5ef-9942-440f-a025-6ce87e0a88be"),
                            ClientId = "client1",
                            ParamId = "CalibrationActive",
                            ParamName = "Height Calibration Active",
                            ParamOrder = 5,
                            ParamViewGroupId = "HeightCalibration",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("aa44396e-f588-4693-b2ac-496b38050ba2"),
                            ClientId = "client1",
                            ParamId = "RetractHeight",
                            ParamName = "Retract Position",
                            ParamOrder = 1,
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("cb0d1c09-7862-411a-af11-1b9ece29e9cc"),
                            ClientId = "client1",
                            ParamId = "RetractPosAtProcessEnd",
                            ParamName = "Retract Position Enable",
                            ParamOrder = 2,
                            ParamViewGroupId = "RetractPosition",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("24951852-7db6-405f-9e60-7d6f99f560f1"),
                            ClientId = "client1",
                            ParamId = "SlagSensitivity",
                            ParamName = "Slag Sensitivity",
                            ParamOrder = 1,
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("a4820e8b-9d10-4611-92b3-201170d86c29"),
                            ClientId = "client1",
                            ParamId = "SlagPostTime",
                            ParamName = "Slag Post Time",
                            ParamOrder = 2,
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("933d23e6-21a2-4fdd-9898-467fa491879f"),
                            ClientId = "client1",
                            ParamId = "SlagCuttingSpeedReduction",
                            ParamName = "Slag Cutting Speed Reduction",
                            ParamOrder = 3,
                            ParamViewGroupId = "Slag",
                            PasswordLevel = 2
                        },
                        new
                        {
                            Id = new Guid("26d65d9c-35b5-401f-a827-bb179eea57d1"),
                            ClientId = "client1",
                            ParamId = "CutO2Blowout",
                            ParamName = "Start Preflow",
                            ParamOrder = 1,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("9b982a83-6a1f-4702-990d-47bdb641c8c3"),
                            ClientId = "client1",
                            ParamId = "CutO2BlowoutBreak",
                            ParamName = "Break Preflow",
                            ParamOrder = 2,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("a025322e-ca13-4c82-a2e6-5938f6fd53f6"),
                            ClientId = "client1",
                            ParamId = "CutO2BlowoutActive",
                            ParamName = "Preflow active",
                            ParamOrder = 3,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("1f9aae96-7c03-401d-8d06-c696f74cd5b7"),
                            ClientId = "client1",
                            ParamId = "CurrCutO2BlowoutTime",
                            ParamName = "Preflow active time",
                            ParamOrder = 4,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("bfbe294b-1f35-489e-8a3f-45745034bd30"),
                            ClientId = "client1",
                            ParamId = "CutO2BlowOutTime",
                            ParamName = "PreFlow Time",
                            ParamOrder = 5,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("13c79f1d-9a6b-4ecc-9a74-a1ca61141a97"),
                            ClientId = "client1",
                            ParamId = "CutO2BlowOutPressure",
                            ParamName = "PreFlow Pressure",
                            ParamOrder = 6,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("12f02e2a-13a5-42cd-a96b-92bc0e5d1d5f"),
                            ClientId = "client1",
                            ParamId = "CutO2BlowOutTimeOut",
                            ParamName = "PreFlow Timeout",
                            ParamOrder = 7,
                            ParamViewGroupId = "PreFlow",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("a6d21455-a576-42b0-a8a8-6457b49ecd16"),
                            ClientId = "client1",
                            ParamId = "HeightPierce",
                            ParamName = "Piercing with Height Control",
                            ParamOrder = 1,
                            ParamViewGroupId = "Piercing",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("8dd8a7c6-755a-46ab-890d-5a185fcf6af9"),
                            ClientId = "client1",
                            ParamId = "PiercingDetection",
                            ParamName = "Piercing detection",
                            ParamOrder = 2,
                            ParamViewGroupId = "Piercing",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("9a218e58-7134-4301-b217-d68cd4e42554"),
                            ClientId = "client1",
                            ParamId = "Dynamic",
                            ParamName = "Dynamic",
                            ParamOrder = 1,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 1
                        },
                        new
                        {
                            Id = new Guid("77fd5e16-26ba-41b3-984b-77a2f19316ad"),
                            ClientId = "client1",
                            ParamId = "ClearanceCtrlOff",
                            ParamName = "Height Control Active",
                            ParamOrder = 2,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("0b30661f-2ba8-4207-a4c5-d6d397200886"),
                            ClientId = "client1",
                            ParamId = "LinearDrivePosition",
                            ParamName = "Position",
                            ParamOrder = 3,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("fa3ef184-1815-482f-8aa0-89169a33be84"),
                            ClientId = "client1",
                            ParamId = "Off",
                            ParamName = "Off",
                            ParamOrder = 4,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("95055160-cb86-4fc4-9f93-f3e71e40cfbe"),
                            ClientId = "client1",
                            ParamId = "HeightPreHeat",
                            ParamName = "Preheating",
                            ParamOrder = 5,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("481866da-39b6-44b6-86a2-eba5dbd67a7b"),
                            ClientId = "client1",
                            ParamId = "HeightPierce",
                            ParamName = "Piercing",
                            ParamOrder = 6,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        },
                        new
                        {
                            Id = new Guid("ba3d2c34-2600-4466-8ba2-2ac39f663298"),
                            ClientId = "client1",
                            ParamId = "HeightCut",
                            ParamName = "Cutting",
                            ParamOrder = 7,
                            ParamViewGroupId = "HeightControl",
                            PasswordLevel = 0
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParamViewGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParamViewGroups");

                    b.HasData(
                        new
                        {
                            Id = "HeightCalibration",
                            GroupName = "Height Calibration",
                            GroupOrder = 1
                        },
                        new
                        {
                            Id = "RetractPosition",
                            GroupName = "Retract Position",
                            GroupOrder = 2
                        },
                        new
                        {
                            Id = "Slag",
                            GroupName = "Slag",
                            GroupOrder = 3
                        },
                        new
                        {
                            Id = "PreFlow",
                            GroupName = "Pre Flow",
                            GroupOrder = 4
                        },
                        new
                        {
                            Id = "Piercing",
                            GroupName = "Piercing",
                            GroupOrder = 5
                        },
                        new
                        {
                            Id = "HeightControl",
                            GroupName = "Height Control",
                            GroupOrder = 6
                        },
                        new
                        {
                            Id = "HeightCalibration_client1",
                            GroupName = "Height Calibration",
                            GroupOrder = 1
                        },
                        new
                        {
                            Id = "RetractPosition_client1",
                            GroupName = "Retract Position",
                            GroupOrder = 3
                        },
                        new
                        {
                            Id = "Slag_client1",
                            GroupName = "Slag",
                            GroupOrder = 2
                        },
                        new
                        {
                            Id = "PreFlow_client1",
                            GroupName = "Pre Flow",
                            GroupOrder = 4
                        },
                        new
                        {
                            Id = "Piercing_client1",
                            GroupName = "Piercing",
                            GroupOrder = 5
                        },
                        new
                        {
                            Id = "HeightControl_client1",
                            GroupName = "Height Control",
                            GroupOrder = 6
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.DynParams", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ConstParams", "ConstParams")
                        .WithMany("DynParams")
                        .HasForeignKey("ConstParamsId");

                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", "ParameterDataInfo")
                        .WithMany("DynParams")
                        .HasForeignKey("ParameterDataInfoId");

                    b.Navigation("ConstParams");

                    b.Navigation("ParameterDataInfo");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.LiveParams", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", "ParameterDataInfo")
                        .WithMany()
                        .HasForeignKey("ParameterDataInfoId");

                    b.Navigation("ParameterDataInfo");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterData", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.APCDevice", "APCDevice")
                        .WithMany("ParameterDatas")
                        .HasForeignKey("APCDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.DynParams", "DynParams")
                        .WithMany("ParameterDatas")
                        .HasForeignKey("DynParamsId");

                    b.Navigation("APCDevice");

                    b.Navigation("DynParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParamSettings", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.APCHardware.ParamViewGroup", "ParamViewGroup")
                        .WithMany()
                        .HasForeignKey("ParamViewGroupId");

                    b.Navigation("ParamViewGroup");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.APCDevice", b =>
                {
                    b.Navigation("ParameterDatas");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ConstParams", b =>
                {
                    b.Navigation("DynParams");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.DynParams", b =>
                {
                    b.Navigation("ParameterDatas");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.APCHardware.ParameterDataInfo", b =>
                {
                    b.Navigation("DynParams");
                });
#pragma warning restore 612, 618
        }
    }
}
