//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IhtApcWebServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IhtApcWebServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publish.
        /// </summary>
        internal static string ApplicationFolder {
            get {
                return ResourceManager.GetString("ApplicationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppInfoData.xml.
        /// </summary>
        internal static string FileNameAppInfoData {
            get {
                return ResourceManager.GetString("FileNameAppInfoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IhtApcApplication.exe.config.
        /// </summary>
        internal static string FileNameConfigFile {
            get {
                return ResourceManager.GetString("FileNameConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IhtApcApplicationPre.exe.config.
        /// </summary>
        internal static string FileNameConfigFilePre {
            get {
                return ResourceManager.GetString("FileNameConfigFilePre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CuttingData.db.
        /// </summary>
        internal static string FileNameDataBase {
            get {
                return ResourceManager.GetString("FileNameDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APCHardware.db.
        /// </summary>
        internal static string FileNameSettingsData {
            get {
                return ResourceManager.GetString("FileNameSettingsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string FolderArchive {
            get {
                return ResourceManager.GetString("FolderArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CutCycleData.
        /// </summary>
        internal static string FolderCutCycleData {
            get {
                return ResourceManager.GetString("FolderCutCycleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBase.
        /// </summary>
        internal static string FolderDataBase {
            get {
                return ResourceManager.GetString("FolderDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceData.
        /// </summary>
        internal static string FolderDeviceData {
            get {
                return ResourceManager.GetString("FolderDeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadToolSetup.
        /// </summary>
        internal static string FolderDownloadToolSetup {
            get {
                return ResourceManager.GetString("FolderDownloadToolSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorData.
        /// </summary>
        internal static string FolderErrorData {
            get {
                return ResourceManager.GetString("FolderErrorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FdtiUsbConverterSetup.
        /// </summary>
        internal static string FolderFdtiUsbConverterSetup {
            get {
                return ResourceManager.GetString("FolderFdtiUsbConverterSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpData.
        /// </summary>
        internal static string FolderHelpData {
            get {
                return ResourceManager.GetString("FolderHelpData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HistogramData.
        /// </summary>
        internal static string FolderHistogramData {
            get {
                return ResourceManager.GetString("FolderHistogramData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IHT Automation.
        /// </summary>
        internal static string FolderManufacturer {
            get {
                return ResourceManager.GetString("FolderManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APC Autogen Process Control.
        /// </summary>
        internal static string FolderProductName {
            get {
                return ResourceManager.GetString("FolderProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProlificUsbConverterSetup.
        /// </summary>
        internal static string FolderProlificUsbConverterSetup {
            get {
                return ResourceManager.GetString("FolderProlificUsbConverterSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusData.
        /// </summary>
        internal static string FolderStatusData {
            get {
                return ResourceManager.GetString("FolderStatusData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusInfoData.
        /// </summary>
        internal static string FolderStatusInfoData {
            get {
                return ResourceManager.GetString("FolderStatusInfoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string FolderUser {
            get {
                return ResourceManager.GetString("FolderUser", resourceCulture);
            }
        }
    }
}
