// <auto-generated />
using System;
using BlazorServerHost.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServerHost.Data.Migrations.APCHardwareMoq
{
    [DbContext(typeof(APCHardwareMoqDBContext))]
    [Migration("20220609114436_Create_Schema_AndSeed")]
    partial class Create_Schema_AndSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMoq.APCDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Num")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("APCDevices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("559a2da5-3411-4366-854b-20b6d8178e9a"),
                            Name = "APCDevice_1",
                            Num = 1
                        },
                        new
                        {
                            Id = new Guid("c6709981-56dd-4ad1-ae3a-ff1b7f17daa3"),
                            Name = "APCDevice_2",
                            Num = 2
                        },
                        new
                        {
                            Id = new Guid("99626c44-cb1a-42d7-bfa1-78413e673171"),
                            Name = "APCDevice_3",
                            Num = 3
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMoq.ConstParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConstParams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39eb9794-3f48-4697-a4ed-1d8a057c4416"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("95ed9b31-ecb9-48ef-a47b-d2f55a31bdae"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("698633ef-5c33-44b0-948e-210c0bfdea76"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("cd2528ed-4dab-4aa4-a78c-9a27c0408aab"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("c151fafa-b89c-4f7b-b7df-f4a3600da34e"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("c2edb00c-f669-4c9b-af2f-35268fb8e544"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("e306b175-a16a-4909-803c-f349e169ba9a"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("e81e66f1-e32b-497f-8803-54c7b0487420"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("9e646492-4a60-48e9-ae33-b48fab8517c0"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("b76b7f6e-ce46-44c6-8817-42c7e0ce49cd"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("b9a85cab-1229-411b-ae28-7188ddf2587e"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("42503352-70f2-4153-849a-07068e9b38a0"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("df9b8e62-e002-4431-88aa-cf00e3a080d4"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("403b69bc-a914-4aa2-87f8-3ec9ef263ebd"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("5aaba64d-b8e9-41c7-a2e9-698d43d6d63e"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("e86c865e-7190-4fa0-97c5-3d8e4637eda3"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("a0afd718-0205-4296-bbd2-6723a1e11bf8"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("f800a09b-b417-4907-a13c-156914f8d4e1"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("0ce26fd4-afb2-4ea6-8dfe-7dff8a6a9e67"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("26759469-5332-4c8a-8428-3c4c82b7f90a"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("59b62a7f-8dbc-4c13-9362-b3b0a4be80fa"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("e9b5253e-5a78-4240-9087-16e2d44a4401"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("85d09e09-c62d-4adc-9aad-c1bafd857777"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("a4bde09a-edca-4765-b1dd-818ab0c627da"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("c0e534a6-6113-405d-a8b6-510a17fa9d0a"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("ac7802f1-8e00-4284-bc14-5edbfc5092d1"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("1753cd3d-2228-4efa-a3d1-c87cd690781c"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("7a34ad52-2e53-4ea5-aeaf-2f835f41f69d"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("831f67c7-32d3-4f07-8468-97eebf2a79da"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("6b332ba7-f3e6-4662-84a8-beebf4873d79"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMoq.DynParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConstParamsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConstParamsId");

                    b.ToTable("DynParams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a3f5f79-02b8-4bd3-8e70-28822f5d6d55"),
                            ConstParamsId = new Guid("39eb9794-3f48-4697-a4ed-1d8a057c4416"),
                            ParamId = 3,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("b3a334b6-07cf-4d13-ad72-2fee102bbfd5"),
                            ConstParamsId = new Guid("95ed9b31-ecb9-48ef-a47b-d2f55a31bdae"),
                            ParamId = 4,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("9db1cb54-69f6-4a5e-8854-015771be0ad1"),
                            ConstParamsId = new Guid("698633ef-5c33-44b0-948e-210c0bfdea76"),
                            ParamId = 5,
                            Value = 4000
                        },
                        new
                        {
                            Id = new Guid("1fea01f3-e73f-43db-9a8e-ecfac3001308"),
                            ConstParamsId = new Guid("cd2528ed-4dab-4aa4-a78c-9a27c0408aab"),
                            ParamId = 8,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("8ff42bee-1534-4d33-b9ab-e7a57d98d62f"),
                            ConstParamsId = new Guid("c151fafa-b89c-4f7b-b7df-f4a3600da34e"),
                            ParamId = 9,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("ce489ab4-47a4-4fae-ae0f-1e1c95fa83c8"),
                            ConstParamsId = new Guid("c2edb00c-f669-4c9b-af2f-35268fb8e544"),
                            ParamId = 10,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("b5b74f54-c846-4cb9-a193-6bf9d070a0cb"),
                            ConstParamsId = new Guid("e306b175-a16a-4909-803c-f349e169ba9a"),
                            ParamId = 11,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("6f89d682-f6ab-449c-a1c2-e67c1980e978"),
                            ConstParamsId = new Guid("e81e66f1-e32b-497f-8803-54c7b0487420"),
                            ParamId = 12,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("70e3ede2-3405-46fd-a831-27a8bcf48173"),
                            ConstParamsId = new Guid("9e646492-4a60-48e9-ae33-b48fab8517c0"),
                            ParamId = 7,
                            Value = 1500
                        },
                        new
                        {
                            Id = new Guid("d5e085a7-f928-4bb6-844d-f46106d61ac4"),
                            ConstParamsId = new Guid("b76b7f6e-ce46-44c6-8817-42c7e0ce49cd"),
                            ParamId = 8,
                            Value = 6000
                        },
                        new
                        {
                            Id = new Guid("a7058bf8-3404-470b-9169-1d90370e4d48"),
                            ConstParamsId = new Guid("b9a85cab-1229-411b-ae28-7188ddf2587e"),
                            ParamId = 3,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("1738306e-53e4-410f-9af0-71ca5604e475"),
                            ConstParamsId = new Guid("42503352-70f2-4153-849a-07068e9b38a0"),
                            ParamId = 4,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("125a8486-bde7-40a1-b2d3-4b2d14d11fb4"),
                            ConstParamsId = new Guid("df9b8e62-e002-4431-88aa-cf00e3a080d4"),
                            ParamId = 5,
                            Value = 4000
                        },
                        new
                        {
                            Id = new Guid("86276a07-e9d7-484d-a522-743dbeb4cbfa"),
                            ConstParamsId = new Guid("403b69bc-a914-4aa2-87f8-3ec9ef263ebd"),
                            ParamId = 8,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("d4e684a1-ed85-4ec8-8aff-9db280b586ba"),
                            ConstParamsId = new Guid("5aaba64d-b8e9-41c7-a2e9-698d43d6d63e"),
                            ParamId = 9,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("b14a4fbd-c865-49a8-8ead-96c54cfd9ba5"),
                            ConstParamsId = new Guid("e86c865e-7190-4fa0-97c5-3d8e4637eda3"),
                            ParamId = 10,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("b5b97f1a-556e-4853-be02-87312a174023"),
                            ConstParamsId = new Guid("a0afd718-0205-4296-bbd2-6723a1e11bf8"),
                            ParamId = 11,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("535e0656-cc96-4274-bcf4-ae40bb584633"),
                            ConstParamsId = new Guid("f800a09b-b417-4907-a13c-156914f8d4e1"),
                            ParamId = 12,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("728ba1fc-182a-44c8-847e-2833936f50aa"),
                            ConstParamsId = new Guid("0ce26fd4-afb2-4ea6-8dfe-7dff8a6a9e67"),
                            ParamId = 7,
                            Value = 1500
                        },
                        new
                        {
                            Id = new Guid("b87ec1d1-ff53-47fd-9f39-46bacd4b397b"),
                            ConstParamsId = new Guid("26759469-5332-4c8a-8428-3c4c82b7f90a"),
                            ParamId = 8,
                            Value = 6000
                        },
                        new
                        {
                            Id = new Guid("9f5f5442-dac5-4c74-bffa-2916a62ff638"),
                            ConstParamsId = new Guid("59b62a7f-8dbc-4c13-9362-b3b0a4be80fa"),
                            ParamId = 3,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("8351086a-7c45-475f-b490-41d2584e2767"),
                            ConstParamsId = new Guid("e9b5253e-5a78-4240-9087-16e2d44a4401"),
                            ParamId = 4,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("8e52eb3f-17a5-4af0-8efc-876a176dff34"),
                            ConstParamsId = new Guid("85d09e09-c62d-4adc-9aad-c1bafd857777"),
                            ParamId = 5,
                            Value = 4000
                        },
                        new
                        {
                            Id = new Guid("c0b6c7e5-5584-41f0-8e42-49393b3280d3"),
                            ConstParamsId = new Guid("a4bde09a-edca-4765-b1dd-818ab0c627da"),
                            ParamId = 8,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("2a8d2962-bd33-43bd-8464-618944c97d1c"),
                            ConstParamsId = new Guid("c0e534a6-6113-405d-a8b6-510a17fa9d0a"),
                            ParamId = 9,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("b11ea890-e0f6-482d-8a95-7d0f87451c03"),
                            ConstParamsId = new Guid("ac7802f1-8e00-4284-bc14-5edbfc5092d1"),
                            ParamId = 10,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("3e5eaef8-2082-4375-8c26-da2024fd54e1"),
                            ConstParamsId = new Guid("1753cd3d-2228-4efa-a3d1-c87cd690781c"),
                            ParamId = 11,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("ed8857ba-80cf-43d9-98b6-4804c4b7778d"),
                            ConstParamsId = new Guid("7a34ad52-2e53-4ea5-aeaf-2f835f41f69d"),
                            ParamId = 12,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("97221d88-a08c-4cf9-9481-753844a9d812"),
                            ConstParamsId = new Guid("831f67c7-32d3-4f07-8468-97eebf2a79da"),
                            ParamId = 7,
                            Value = 1500
                        },
                        new
                        {
                            Id = new Guid("845efb52-431e-4950-a4d1-d6b904801d27"),
                            ConstParamsId = new Guid("6b332ba7-f3e6-4662-84a8-beebf4873d79"),
                            ParamId = 8,
                            Value = 6000
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMoq.LiveParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LiveParams");
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMoq.ParameterData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("APCDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DynParamsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("APCDeviceId");

                    b.HasIndex("DynParamsId");

                    b.ToTable("ParameterDatas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0c457eb-a986-4820-854d-1c21076702e4"),
                            APCDeviceId = new Guid("559a2da5-3411-4366-854b-20b6d8178e9a"),
                            DynParamsId = new Guid("8a3f5f79-02b8-4bd3-8e70-28822f5d6d55"),
                            ParamName = "Device1_HeatO2Ignition"
                        },
                        new
                        {
                            Id = new Guid("262838bd-abd5-4e58-a9f7-6dbe6378c04c"),
                            APCDeviceId = new Guid("559a2da5-3411-4366-854b-20b6d8178e9a"),
                            DynParamsId = new Guid("b3a334b6-07cf-4d13-ad72-2fee102bbfd5"),
                            ParamName = "Device1_HeatO2PreHeat"
                        },
                        new
                        {
                            Id = new Guid("ffe79783-046d-482c-967a-0fd19771ac29"),
                            APCDeviceId = new Guid("559a2da5-3411-4366-854b-20b6d8178e9a"),
                            DynParamsId = new Guid("9db1cb54-69f6-4a5e-8854-015771be0ad1"),
                            ParamName = "Device1_HeatO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("734d06ea-51bc-4b6b-839e-8ee8681a3a9c"),
                            APCDeviceId = new Guid("559a2da5-3411-4366-854b-20b6d8178e9a"),
                            DynParamsId = new Guid("1fea01f3-e73f-43db-9a8e-ecfac3001308"),
                            ParamName = "Device1_HeatO2Cut"
                        },
                        new
                        {
                            Id = new Guid("59afafea-bfdb-42ba-a2dc-14fd6ba2d711"),
                            APCDeviceId = new Guid("559a2da5-3411-4366-854b-20b6d8178e9a"),
                            DynParamsId = new Guid("8ff42bee-1534-4d33-b9ab-e7a57d98d62f"),
                            ParamName = "Device1_FuelGasIgnition"
                        },
                        new
                        {
                            Id = new Guid("ff811089-1a2b-4052-ba3b-6bd09d1ec394"),
                            APCDeviceId = new Guid("559a2da5-3411-4366-854b-20b6d8178e9a"),
                            DynParamsId = new Guid("ce489ab4-47a4-4fae-ae0f-1e1c95fa83c8"),
                            ParamName = "Device1_FuelGasPreHeat"
                        },
                        new
                        {
                            Id = new Guid("07438aa4-735a-4591-a534-43d6f069f1a1"),
                            APCDeviceId = new Guid("559a2da5-3411-4366-854b-20b6d8178e9a"),
                            DynParamsId = new Guid("b5b74f54-c846-4cb9-a193-6bf9d070a0cb"),
                            ParamName = "Device1_FuelGasPierce"
                        },
                        new
                        {
                            Id = new Guid("bbcb60af-1537-4ad1-baf2-95ee2c727b9d"),
                            APCDeviceId = new Guid("559a2da5-3411-4366-854b-20b6d8178e9a"),
                            DynParamsId = new Guid("6f89d682-f6ab-449c-a1c2-e67c1980e978"),
                            ParamName = "Device1_FuelGasCut"
                        },
                        new
                        {
                            Id = new Guid("8113441a-590a-4eaa-85e0-5bb860706031"),
                            APCDeviceId = new Guid("559a2da5-3411-4366-854b-20b6d8178e9a"),
                            DynParamsId = new Guid("70e3ede2-3405-46fd-a831-27a8bcf48173"),
                            ParamName = "Device1_CutO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("dd7c738f-6c2b-4e8b-9bba-f5e147dad032"),
                            APCDeviceId = new Guid("559a2da5-3411-4366-854b-20b6d8178e9a"),
                            DynParamsId = new Guid("d5e085a7-f928-4bb6-844d-f46106d61ac4"),
                            ParamName = "Device1_CutO2Cut"
                        },
                        new
                        {
                            Id = new Guid("4081b59c-f21c-4e6a-a89c-1e08b1f4d414"),
                            APCDeviceId = new Guid("c6709981-56dd-4ad1-ae3a-ff1b7f17daa3"),
                            DynParamsId = new Guid("a7058bf8-3404-470b-9169-1d90370e4d48"),
                            ParamName = "Device2_HeatO2Ignition"
                        },
                        new
                        {
                            Id = new Guid("a19de9c8-7f7e-40de-a8d3-e4c7689b97b7"),
                            APCDeviceId = new Guid("c6709981-56dd-4ad1-ae3a-ff1b7f17daa3"),
                            DynParamsId = new Guid("1738306e-53e4-410f-9af0-71ca5604e475"),
                            ParamName = "Device2_HeatO2PreHeat"
                        },
                        new
                        {
                            Id = new Guid("6080ebf7-c017-4c6c-b954-8454bafc84bb"),
                            APCDeviceId = new Guid("c6709981-56dd-4ad1-ae3a-ff1b7f17daa3"),
                            DynParamsId = new Guid("125a8486-bde7-40a1-b2d3-4b2d14d11fb4"),
                            ParamName = "Device2_HeatO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("47181095-fd0f-4e18-9b31-3f932f20b35d"),
                            APCDeviceId = new Guid("c6709981-56dd-4ad1-ae3a-ff1b7f17daa3"),
                            DynParamsId = new Guid("86276a07-e9d7-484d-a522-743dbeb4cbfa"),
                            ParamName = "Device2_HeatO2Cut"
                        },
                        new
                        {
                            Id = new Guid("69ce081d-d51c-43e9-a619-f304e7d77e43"),
                            APCDeviceId = new Guid("c6709981-56dd-4ad1-ae3a-ff1b7f17daa3"),
                            DynParamsId = new Guid("d4e684a1-ed85-4ec8-8aff-9db280b586ba"),
                            ParamName = "Device2_FuelGasIgnition"
                        },
                        new
                        {
                            Id = new Guid("607c0400-2c67-4dfb-96ca-fdc3afcc1660"),
                            APCDeviceId = new Guid("c6709981-56dd-4ad1-ae3a-ff1b7f17daa3"),
                            DynParamsId = new Guid("b14a4fbd-c865-49a8-8ead-96c54cfd9ba5"),
                            ParamName = "Device2_FuelGasPreHeat"
                        },
                        new
                        {
                            Id = new Guid("91b6c0ac-fe86-429c-b483-fe8badd8fa26"),
                            APCDeviceId = new Guid("c6709981-56dd-4ad1-ae3a-ff1b7f17daa3"),
                            DynParamsId = new Guid("b5b97f1a-556e-4853-be02-87312a174023"),
                            ParamName = "Device2_FuelGasPierce"
                        },
                        new
                        {
                            Id = new Guid("54cfac38-0372-4089-b902-547ab803f657"),
                            APCDeviceId = new Guid("c6709981-56dd-4ad1-ae3a-ff1b7f17daa3"),
                            DynParamsId = new Guid("535e0656-cc96-4274-bcf4-ae40bb584633"),
                            ParamName = "Device2_FuelGasCut"
                        },
                        new
                        {
                            Id = new Guid("1b06be61-4adf-4458-841c-4475d194557c"),
                            APCDeviceId = new Guid("c6709981-56dd-4ad1-ae3a-ff1b7f17daa3"),
                            DynParamsId = new Guid("728ba1fc-182a-44c8-847e-2833936f50aa"),
                            ParamName = "Device2_CutO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("30a0fc27-6ebf-4326-9841-ffcd2350d90e"),
                            APCDeviceId = new Guid("c6709981-56dd-4ad1-ae3a-ff1b7f17daa3"),
                            DynParamsId = new Guid("b87ec1d1-ff53-47fd-9f39-46bacd4b397b"),
                            ParamName = "Device2_CutO2Cut"
                        },
                        new
                        {
                            Id = new Guid("eff63169-627e-49e3-80c1-3e3e8b70ec73"),
                            APCDeviceId = new Guid("99626c44-cb1a-42d7-bfa1-78413e673171"),
                            DynParamsId = new Guid("9f5f5442-dac5-4c74-bffa-2916a62ff638"),
                            ParamName = "Device3_HeatO2Ignition"
                        },
                        new
                        {
                            Id = new Guid("c108f3c2-c026-4c04-935f-554ee7cee0e3"),
                            APCDeviceId = new Guid("99626c44-cb1a-42d7-bfa1-78413e673171"),
                            DynParamsId = new Guid("8351086a-7c45-475f-b490-41d2584e2767"),
                            ParamName = "Device3_HeatO2PreHeat"
                        },
                        new
                        {
                            Id = new Guid("21e81f17-4f02-4153-aee5-f63d4e05a3e0"),
                            APCDeviceId = new Guid("99626c44-cb1a-42d7-bfa1-78413e673171"),
                            DynParamsId = new Guid("8e52eb3f-17a5-4af0-8efc-876a176dff34"),
                            ParamName = "Device3_HeatO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("9734a4a6-ed84-42f6-971a-b14158f4d45e"),
                            APCDeviceId = new Guid("99626c44-cb1a-42d7-bfa1-78413e673171"),
                            DynParamsId = new Guid("c0b6c7e5-5584-41f0-8e42-49393b3280d3"),
                            ParamName = "Device3_HeatO2Cut"
                        },
                        new
                        {
                            Id = new Guid("4b196434-3b79-4051-ae03-ede50616f5e6"),
                            APCDeviceId = new Guid("99626c44-cb1a-42d7-bfa1-78413e673171"),
                            DynParamsId = new Guid("2a8d2962-bd33-43bd-8464-618944c97d1c"),
                            ParamName = "Device3_FuelGasIgnition"
                        },
                        new
                        {
                            Id = new Guid("f4d54bbb-1b8b-4ca2-a6ff-94c2eeb491a1"),
                            APCDeviceId = new Guid("99626c44-cb1a-42d7-bfa1-78413e673171"),
                            DynParamsId = new Guid("b11ea890-e0f6-482d-8a95-7d0f87451c03"),
                            ParamName = "Device3_FuelGasPreHeat"
                        },
                        new
                        {
                            Id = new Guid("e0027129-08f9-46ab-809f-1a1d4d9b79b4"),
                            APCDeviceId = new Guid("99626c44-cb1a-42d7-bfa1-78413e673171"),
                            DynParamsId = new Guid("3e5eaef8-2082-4375-8c26-da2024fd54e1"),
                            ParamName = "Device3_FuelGasPierce"
                        },
                        new
                        {
                            Id = new Guid("c9d1d3cc-034b-4055-8e68-278dbee5b176"),
                            APCDeviceId = new Guid("99626c44-cb1a-42d7-bfa1-78413e673171"),
                            DynParamsId = new Guid("ed8857ba-80cf-43d9-98b6-4804c4b7778d"),
                            ParamName = "Device3_FuelGasCut"
                        },
                        new
                        {
                            Id = new Guid("36ddcfe7-f514-4db4-ae03-ac4c8aeaa5a6"),
                            APCDeviceId = new Guid("99626c44-cb1a-42d7-bfa1-78413e673171"),
                            DynParamsId = new Guid("97221d88-a08c-4cf9-9481-753844a9d812"),
                            ParamName = "Device3_CutO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("998ce9d1-cd45-4a2e-9f73-7f24d266b047"),
                            APCDeviceId = new Guid("99626c44-cb1a-42d7-bfa1-78413e673171"),
                            DynParamsId = new Guid("845efb52-431e-4950-a4d1-d6b904801d27"),
                            ParamName = "Device3_CutO2Cut"
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMoq.DynParams", b =>
                {
                    b.HasOne("BlazorServerHost.Data.Models.APCHardwareMoq.ConstParams", "ConstParams")
                        .WithMany()
                        .HasForeignKey("ConstParamsId");

                    b.Navigation("ConstParams");
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMoq.ParameterData", b =>
                {
                    b.HasOne("BlazorServerHost.Data.Models.APCHardwareMoq.APCDevice", "APCDevice")
                        .WithMany()
                        .HasForeignKey("APCDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServerHost.Data.Models.APCHardwareMoq.DynParams", "DynParams")
                        .WithMany()
                        .HasForeignKey("DynParamsId");

                    b.Navigation("APCDevice");

                    b.Navigation("DynParams");
                });
#pragma warning restore 612, 618
        }
    }
}
