// <auto-generated />
using System;
using BlazorServerHost.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServerHost.Data.Migrations.APCHardwareMock
{
    [DbContext(typeof(APCHardwareMockDBContext))]
    [Migration("20220722152631_Create_Schema_AndSeed")]
    partial class Create_Schema_AndSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.APCDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Num")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("APCDevices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77136ba4-8b3c-488d-b020-f8a8bdb396d2"),
                            Name = "System",
                            Num = 0
                        },
                        new
                        {
                            Id = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            Name = "APCDevice_1",
                            Num = 1
                        },
                        new
                        {
                            Id = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            Name = "APCDevice_2",
                            Num = 2
                        },
                        new
                        {
                            Id = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            Name = "APCDevice_3",
                            Num = 3
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.ConstParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConstParams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("803d501f-9fbc-41cf-80a1-a34f57a88cb3"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("998ecc3b-ed42-4f24-846a-508fbd052400"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("4842636d-9300-493b-ac34-f341dc09d304"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("e7233157-65f7-4435-8bab-846900de6181"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("736b62ce-64cf-4bc0-838a-c557e40d468a"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("c31813f0-670f-410d-ab5e-d52b8c2063ee"),
                            Max = 100,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("30da327a-fa2e-4260-b11d-b1a4dd3c4159"),
                            Max = 100,
                            Min = 10,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("81af64d9-39d9-4df3-ace6-91a2cd16196a"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("3a48d048-7938-424c-8fe7-5f4734caecbd"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("01037183-d84e-4c57-b60c-5ee378162bd2"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("b9d0fb6d-8e6f-4f35-81f6-809df2182688"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("2d6d66ee-fbb8-4cb1-a675-7bdbe10be6bb"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("629e3d4b-6c02-4ece-a418-8055c7af3779"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("dd3e6832-b422-47af-b43d-e3257213b4e4"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("3bb95b53-b00d-4b9d-8807-236190e22e89"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("9eab57d7-8775-457b-90b5-b57457b802df"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("fdb346c8-c24e-4806-baa4-d67c974e6687"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("a0eb2dc1-51cf-4948-ba6c-227535dce9b2"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("35f2efb1-5acd-44b9-89f9-a38e6e856092"),
                            Max = 1000,
                            Min = 200,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("2f3ad69c-a671-400a-ad89-159a14ec0c84"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("a8840ccb-28da-4a84-ba50-d46e529dc760"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("bf2dfb8b-38cf-4c24-9f7d-8bc22b396f93"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("796adf0a-b85a-4be7-b9e2-f76c604d0d99"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("12f39af7-12bb-4983-a2fc-2a968c92ccc2"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("0e7c7471-e903-4444-a85d-f8a047af9540"),
                            Max = 100,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("268a199a-fa99-4619-b402-71f66910f6c7"),
                            Max = 100,
                            Min = 10,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("85779ea2-05f8-4198-9899-4cfe05a302b9"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("ec5268b5-f45f-48c8-b6ed-d38f5393e889"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("9511c7da-4d6d-406f-bee3-3ae0e41adbb4"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("ca08e9c2-da79-4124-9cce-3d2675462a18"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("3b7175ff-31c7-4ca2-b509-645070233e18"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("17a10e66-7050-402d-a651-1aa9e420294d"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("7e86f23c-6599-47da-99f3-4d2cb8ed87df"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("79b018cb-0054-4c6c-b0a2-c17da6455fa4"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("595293ca-26b6-40bd-8508-9c13e1e86f1c"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("fc836be1-dc04-4a02-b51d-12ec6aa9b4f0"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("2d7343f9-f87c-410b-ba30-44466feda2b9"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("e95d60a0-f5bd-43f2-96bb-71c176942503"),
                            Max = 1000,
                            Min = 200,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("a8715119-26b9-4e48-a14f-40ce49ccffc8"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("2470a24b-1aac-4cd5-9fb1-65ef527c0a80"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("1ddcd4ab-46f7-44e7-91ad-566a7c98cf24"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("82dc7cb2-b0db-4c6f-bab5-ebe038911829"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("302cf3ef-80a2-43c9-8d3a-51a478cdf56b"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("35414ce4-a6a9-4060-88db-bddae8c469e4"),
                            Max = 100,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("fb90317a-4dbc-4dc7-80af-46716e34a2d0"),
                            Max = 100,
                            Min = 10,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("6d8a5a95-dc09-4d95-a933-2348e1e0b83a"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("2cd2b33a-61fe-4f8e-b10c-109676c43f87"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("16f4a8dd-0b4d-4cdb-b6e2-f4c8ccd27d26"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("5735908b-65f9-4097-ad39-d9a867f19aa6"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("55549187-b601-4665-92ab-1e05f1e8621e"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("07d50358-35cf-4de9-a1d4-dca21d605516"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("f1fda7ed-16ea-42bd-aa31-bbdb0f2af6c1"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("0c5cff4b-99e2-4e82-82e5-f543762b5dd7"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("309fe732-860a-4925-9670-b5f5f7fb5284"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("3a6ae67c-b76a-431a-9061-1e96d2ad638a"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("850853d4-b12a-4bb5-980e-3d45a14dc574"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("61e0bf05-4084-40cb-a765-104a782d3964"),
                            Max = 1000,
                            Min = 200,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("6b742bf2-08a2-4255-bcbc-457ed4194ad1"),
                            Max = 500,
                            Min = 0,
                            Step = 25
                        },
                        new
                        {
                            Id = new Guid("87e93ce2-20a3-43d1-aa9f-d6747efc2079"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("ce0895c1-7a59-4c27-872d-0d006a11f2aa"),
                            Max = 3,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("04b0ba3b-c8df-48f3-91fb-5e3654dee29f"),
                            Max = 100,
                            Min = 0,
                            Step = 5
                        },
                        new
                        {
                            Id = new Guid("e7d7d91b-efeb-4b46-9ab7-2754c9a0cca3"),
                            Max = 100,
                            Min = 50,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("edcc944c-50cc-473d-8f04-c6adad734b2c"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("ffee8877-7552-403a-83a4-269df0bc992e"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("bbfb513a-3223-4c26-8633-e624c40c25f4"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("857b3f33-16a8-4fcf-9eb6-9da25ddb406b"),
                            Max = 1,
                            Min = 0,
                            Step = 1
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.DynParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConstParamsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConstParamsId");

                    b.ToTable("DynParams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b98e3fb-cb13-4974-8ad4-599776a1a3de"),
                            ConstParamsId = new Guid("803d501f-9fbc-41cf-80a1-a34f57a88cb3"),
                            ParamId = 3,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("76f8cde7-7e2b-4816-a953-26b69ecc031b"),
                            ConstParamsId = new Guid("998ecc3b-ed42-4f24-846a-508fbd052400"),
                            ParamId = 4,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("1eb8908a-1968-4f7a-8904-fd683da0961a"),
                            ConstParamsId = new Guid("4842636d-9300-493b-ac34-f341dc09d304"),
                            ParamId = 5,
                            Value = 4000
                        },
                        new
                        {
                            Id = new Guid("e62f9be3-4530-41f6-ab7f-481a3ff36169"),
                            ConstParamsId = new Guid("e7233157-65f7-4435-8bab-846900de6181"),
                            ParamId = 6,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("e8543019-4f1b-4527-a4a7-ba32450105fc"),
                            ConstParamsId = new Guid("629e3d4b-6c02-4ece-a418-8055c7af3779"),
                            ParamId = 9,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("d63c2661-3215-4436-9255-8e62668951ea"),
                            ConstParamsId = new Guid("dd3e6832-b422-47af-b43d-e3257213b4e4"),
                            ParamId = 10,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("bb96576d-dd41-4776-ae6a-927097057dcc"),
                            ConstParamsId = new Guid("3bb95b53-b00d-4b9d-8807-236190e22e89"),
                            ParamId = 11,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("36517e32-d592-4c96-a4d9-49c52da819fc"),
                            ConstParamsId = new Guid("9eab57d7-8775-457b-90b5-b57457b802df"),
                            ParamId = 12,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("9d6487eb-d3bc-4687-9b27-45c5339a8f52"),
                            ConstParamsId = new Guid("fdb346c8-c24e-4806-baa4-d67c974e6687"),
                            ParamId = 7,
                            Value = 1500
                        },
                        new
                        {
                            Id = new Guid("d30a120e-53d8-4652-8ca9-174960e746a1"),
                            ConstParamsId = new Guid("a0eb2dc1-51cf-4948-ba6c-227535dce9b2"),
                            ParamId = 8,
                            Value = 6000
                        },
                        new
                        {
                            Id = new Guid("fdd9435b-5cfb-408b-bc08-8ba84cbf9aa2"),
                            ConstParamsId = new Guid("35f2efb1-5acd-44b9-89f9-a38e6e856092"),
                            ParamId = 20,
                            Value = 500
                        },
                        new
                        {
                            Id = new Guid("d4808111-46b4-4310-a30b-2f0bc5e66bff"),
                            ConstParamsId = new Guid("736b62ce-64cf-4bc0-838a-c557e40d468a"),
                            ParamId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("9e09daef-4a50-4d70-ae01-5aa3c8028b67"),
                            ConstParamsId = new Guid("c31813f0-670f-410d-ab5e-d52b8c2063ee"),
                            ParamId = 9,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("d9d65f61-b07a-45cb-b513-eeda945023da"),
                            ConstParamsId = new Guid("30da327a-fa2e-4260-b11d-b1a4dd3c4159"),
                            ParamId = 4,
                            Value = 35
                        },
                        new
                        {
                            Id = new Guid("f02c2c84-8bd5-4b85-b137-4404b2031947"),
                            ConstParamsId = new Guid("81af64d9-39d9-4df3-ace6-91a2cd16196a"),
                            ParamId = 5,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("de174409-1c4d-45e2-abe8-0d6c19dd9856"),
                            ConstParamsId = new Guid("3a48d048-7938-424c-8fe7-5f4734caecbd"),
                            ParamId = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("006d7287-6eac-416a-b736-98043f4c9c42"),
                            ConstParamsId = new Guid("01037183-d84e-4c57-b60c-5ee378162bd2"),
                            ParamId = 1,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("67de7b28-2615-4e05-9a18-7d0709ed92cc"),
                            ConstParamsId = new Guid("b9d0fb6d-8e6f-4f35-81f6-809df2182688"),
                            ParamId = 2,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("9d3ecf58-222e-446b-addd-7c013ca96634"),
                            ConstParamsId = new Guid("2d6d66ee-fbb8-4cb1-a675-7bdbe10be6bb"),
                            ParamId = 3,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("de94ded5-eab9-4ec7-bf24-cc75c4a07f81"),
                            ConstParamsId = new Guid("2f3ad69c-a671-400a-ad89-159a14ec0c84"),
                            ParamId = 3,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("72671a0c-f182-4ee7-973f-0971c2191086"),
                            ConstParamsId = new Guid("a8840ccb-28da-4a84-ba50-d46e529dc760"),
                            ParamId = 4,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("a2dcb6b8-963c-4823-b188-941a01f2bcac"),
                            ConstParamsId = new Guid("bf2dfb8b-38cf-4c24-9f7d-8bc22b396f93"),
                            ParamId = 5,
                            Value = 4000
                        },
                        new
                        {
                            Id = new Guid("d3e0f5ba-5f06-4b3e-b283-0b3047209fbc"),
                            ConstParamsId = new Guid("796adf0a-b85a-4be7-b9e2-f76c604d0d99"),
                            ParamId = 6,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("1773e2be-3151-4fb3-bfde-176e3ef750cb"),
                            ConstParamsId = new Guid("17a10e66-7050-402d-a651-1aa9e420294d"),
                            ParamId = 9,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("0aacca5b-bb83-4947-9571-947e2ef9f70f"),
                            ConstParamsId = new Guid("7e86f23c-6599-47da-99f3-4d2cb8ed87df"),
                            ParamId = 10,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("c8f8d3ef-b4cb-46f0-a5e5-d9b5e320b68c"),
                            ConstParamsId = new Guid("79b018cb-0054-4c6c-b0a2-c17da6455fa4"),
                            ParamId = 11,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("3bf5ea1a-4aeb-482a-8c8f-7aa4ffe0729b"),
                            ConstParamsId = new Guid("595293ca-26b6-40bd-8508-9c13e1e86f1c"),
                            ParamId = 12,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("07431172-2134-443d-a786-371c02c93d62"),
                            ConstParamsId = new Guid("fc836be1-dc04-4a02-b51d-12ec6aa9b4f0"),
                            ParamId = 7,
                            Value = 1500
                        },
                        new
                        {
                            Id = new Guid("bbd3cb20-577d-4e38-a80b-fb507e8e8d89"),
                            ConstParamsId = new Guid("2d7343f9-f87c-410b-ba30-44466feda2b9"),
                            ParamId = 8,
                            Value = 6000
                        },
                        new
                        {
                            Id = new Guid("af648d26-0fc5-4c1a-ba11-97520306c41e"),
                            ConstParamsId = new Guid("e95d60a0-f5bd-43f2-96bb-71c176942503"),
                            ParamId = 20,
                            Value = 500
                        },
                        new
                        {
                            Id = new Guid("98391455-cb1f-4284-8f19-c8ad4f7951ad"),
                            ConstParamsId = new Guid("12f39af7-12bb-4983-a2fc-2a968c92ccc2"),
                            ParamId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("37425a3a-0fcf-41af-8584-88eb5d720629"),
                            ConstParamsId = new Guid("0e7c7471-e903-4444-a85d-f8a047af9540"),
                            ParamId = 9,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("ffb7793f-b0a4-450f-9f0b-419eab5e74d5"),
                            ConstParamsId = new Guid("268a199a-fa99-4619-b402-71f66910f6c7"),
                            ParamId = 4,
                            Value = 35
                        },
                        new
                        {
                            Id = new Guid("96c95aee-c377-4c12-85d4-3fd61f94a16b"),
                            ConstParamsId = new Guid("85779ea2-05f8-4198-9899-4cfe05a302b9"),
                            ParamId = 5,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("05d06dd5-9c03-43e5-b9ac-c99baa414058"),
                            ConstParamsId = new Guid("ec5268b5-f45f-48c8-b6ed-d38f5393e889"),
                            ParamId = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("65bde5c8-77e9-4166-b7b2-3029d2f2e866"),
                            ConstParamsId = new Guid("9511c7da-4d6d-406f-bee3-3ae0e41adbb4"),
                            ParamId = 1,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("1687d4c8-c968-4177-a2f5-c98e375b2239"),
                            ConstParamsId = new Guid("ca08e9c2-da79-4124-9cce-3d2675462a18"),
                            ParamId = 2,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("d6527850-1dca-4ac5-a220-0f4ef927c5fa"),
                            ConstParamsId = new Guid("3b7175ff-31c7-4ca2-b509-645070233e18"),
                            ParamId = 3,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("3bb4d636-9373-4584-8a30-65b1f7044099"),
                            ConstParamsId = new Guid("a8715119-26b9-4e48-a14f-40ce49ccffc8"),
                            ParamId = 3,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("9bb7baeb-c1a9-42a8-b23d-fa8a7b641516"),
                            ConstParamsId = new Guid("2470a24b-1aac-4cd5-9fb1-65ef527c0a80"),
                            ParamId = 4,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("8436b716-b197-469c-bdce-894173d336b0"),
                            ConstParamsId = new Guid("1ddcd4ab-46f7-44e7-91ad-566a7c98cf24"),
                            ParamId = 5,
                            Value = 4000
                        },
                        new
                        {
                            Id = new Guid("722cfe71-d7fe-4721-bf37-169451617855"),
                            ConstParamsId = new Guid("82dc7cb2-b0db-4c6f-bab5-ebe038911829"),
                            ParamId = 6,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("90863bad-eda3-4320-858b-a8a84a5b0974"),
                            ConstParamsId = new Guid("07d50358-35cf-4de9-a1d4-dca21d605516"),
                            ParamId = 9,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("b38d97c5-1a56-4448-a457-36ce9ae21539"),
                            ConstParamsId = new Guid("f1fda7ed-16ea-42bd-aa31-bbdb0f2af6c1"),
                            ParamId = 10,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("1fcf6d0a-5651-4daa-9b13-5c8c4bf9d12b"),
                            ConstParamsId = new Guid("0c5cff4b-99e2-4e82-82e5-f543762b5dd7"),
                            ParamId = 11,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("5b981638-4462-47f9-8390-8483fbb6a819"),
                            ConstParamsId = new Guid("309fe732-860a-4925-9670-b5f5f7fb5284"),
                            ParamId = 12,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("d3f5b3f0-097f-4652-8938-deeae91da1e9"),
                            ConstParamsId = new Guid("3a6ae67c-b76a-431a-9061-1e96d2ad638a"),
                            ParamId = 7,
                            Value = 1500
                        },
                        new
                        {
                            Id = new Guid("2b71293d-d4a6-4df0-88aa-5c7d02a2790a"),
                            ConstParamsId = new Guid("850853d4-b12a-4bb5-980e-3d45a14dc574"),
                            ParamId = 8,
                            Value = 6000
                        },
                        new
                        {
                            Id = new Guid("2f9c2b2b-3858-4523-b90e-248ea8a1db0d"),
                            ConstParamsId = new Guid("61e0bf05-4084-40cb-a765-104a782d3964"),
                            ParamId = 20,
                            Value = 500
                        },
                        new
                        {
                            Id = new Guid("96cf84ad-6ec2-482a-b9c6-222b7f8ae1fe"),
                            ConstParamsId = new Guid("302cf3ef-80a2-43c9-8d3a-51a478cdf56b"),
                            ParamId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("44c772ad-22d2-4f02-a418-9b746766ed2a"),
                            ConstParamsId = new Guid("35414ce4-a6a9-4060-88db-bddae8c469e4"),
                            ParamId = 9,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("84a52d5d-6719-4985-9631-32076e345a4c"),
                            ConstParamsId = new Guid("fb90317a-4dbc-4dc7-80af-46716e34a2d0"),
                            ParamId = 4,
                            Value = 35
                        },
                        new
                        {
                            Id = new Guid("8ee97e31-ef78-4aa8-b48a-9cb998b1bc14"),
                            ConstParamsId = new Guid("6d8a5a95-dc09-4d95-a933-2348e1e0b83a"),
                            ParamId = 5,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("0736800c-d2aa-41d6-9c69-af21b1d666e1"),
                            ConstParamsId = new Guid("2cd2b33a-61fe-4f8e-b10c-109676c43f87"),
                            ParamId = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("63b78f1a-4831-4eaa-a2a2-e64540a3ae3b"),
                            ConstParamsId = new Guid("16f4a8dd-0b4d-4cdb-b6e2-f4c8ccd27d26"),
                            ParamId = 1,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("f99b7a6e-25c9-40ae-87c2-af300228fc09"),
                            ConstParamsId = new Guid("5735908b-65f9-4097-ad39-d9a867f19aa6"),
                            ParamId = 2,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("3095b08c-0fb9-4177-a511-77d842412710"),
                            ConstParamsId = new Guid("55549187-b601-4665-92ab-1e05f1e8621e"),
                            ParamId = 3,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("6a91bddd-7720-4f5d-a677-a0eca0488814"),
                            ConstParamsId = new Guid("6b742bf2-08a2-4255-bcbc-457ed4194ad1"),
                            ParamId = 0,
                            Value = 100
                        },
                        new
                        {
                            Id = new Guid("15b23a1b-0b77-4071-86fb-d95e96db1497"),
                            ConstParamsId = new Guid("87e93ce2-20a3-43d1-aa9f-d6747efc2079"),
                            ParamId = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("7e1f090e-7366-42ba-a11d-d3853d97f7a5"),
                            ConstParamsId = new Guid("ce0895c1-7a59-4c27-872d-0d006a11f2aa"),
                            ParamId = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("d1a5797b-f0ca-42bc-8af5-2ca52e25ff19"),
                            ConstParamsId = new Guid("04b0ba3b-c8df-48f3-91fb-5e3654dee29f"),
                            ParamId = 11,
                            Value = 20
                        },
                        new
                        {
                            Id = new Guid("fb9b52e0-54c4-4c15-aa64-e542bea25a75"),
                            ConstParamsId = new Guid("e7d7d91b-efeb-4b46-9ab7-2754c9a0cca3"),
                            ParamId = 4,
                            Value = 100
                        },
                        new
                        {
                            Id = new Guid("e84acbad-2150-4f9e-8e7f-07ceb4e1b910"),
                            ConstParamsId = new Guid("edcc944c-50cc-473d-8f04-c6adad734b2c"),
                            ParamId = 1,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("59fc04e6-96fb-4156-a6a1-8e3445534945"),
                            ConstParamsId = new Guid("ffee8877-7552-403a-83a4-269df0bc992e"),
                            ParamId = 2,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("32e1f3e0-b804-4c21-99f7-82f39c580417"),
                            ConstParamsId = new Guid("bbfb513a-3223-4c26-8633-e624c40c25f4"),
                            ParamId = 3,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("691230d6-86cb-4f1a-9ca9-affba7be70dd"),
                            ConstParamsId = new Guid("857b3f33-16a8-4fcf-9eb6-9da25ddb406b"),
                            ParamId = 4,
                            Value = 0
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.LiveParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LiveParams");
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.ParameterData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("APCDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DynParamsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("APCDeviceId");

                    b.HasIndex("DynParamsId");

                    b.ToTable("ParameterDatas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3bfff98-aa82-4833-b3b3-3d0bcb534e13"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("4b98e3fb-cb13-4974-8ad4-599776a1a3de"),
                            ParamGroupId = 1,
                            ParamName = "Device1_HeatO2Ignition"
                        },
                        new
                        {
                            Id = new Guid("59d2c21d-4655-46c7-9014-ab216c0b7d61"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("76f8cde7-7e2b-4816-a953-26b69ecc031b"),
                            ParamGroupId = 1,
                            ParamName = "Device1_HeatO2PreHeat"
                        },
                        new
                        {
                            Id = new Guid("4a127d3f-938a-4f63-bd23-b83b72c38dbc"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("1eb8908a-1968-4f7a-8904-fd683da0961a"),
                            ParamGroupId = 1,
                            ParamName = "Device1_HeatO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("7abd1da2-792b-46c3-9602-8477dbd96496"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("e62f9be3-4530-41f6-ab7f-481a3ff36169"),
                            ParamGroupId = 1,
                            ParamName = "Device1_HeatO2Cut"
                        },
                        new
                        {
                            Id = new Guid("f6ee0b50-9eed-4683-823d-939b5bd04f5e"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("e8543019-4f1b-4527-a4a7-ba32450105fc"),
                            ParamGroupId = 1,
                            ParamName = "Device1_FuelGasIgnition"
                        },
                        new
                        {
                            Id = new Guid("a1c1f23b-1385-4ee5-9380-11130cd6fcb2"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("d63c2661-3215-4436-9255-8e62668951ea"),
                            ParamGroupId = 1,
                            ParamName = "Device1_FuelGasPreHeat"
                        },
                        new
                        {
                            Id = new Guid("bcf67ed4-5dd6-4190-9cfe-54990c664be1"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("bb96576d-dd41-4776-ae6a-927097057dcc"),
                            ParamGroupId = 1,
                            ParamName = "Device1_FuelGasPierce"
                        },
                        new
                        {
                            Id = new Guid("d5f29528-a4da-4084-98a4-6efa109f4fb8"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("36517e32-d592-4c96-a4d9-49c52da819fc"),
                            ParamGroupId = 1,
                            ParamName = "Device1_FuelGasCut"
                        },
                        new
                        {
                            Id = new Guid("79250f63-f14d-4691-ad89-3d39e6bc55e7"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("9d6487eb-d3bc-4687-9b27-45c5339a8f52"),
                            ParamGroupId = 1,
                            ParamName = "Device1_CutO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("88797512-6765-4ad3-82f2-2aeed21fd797"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("d30a120e-53d8-4652-8ca9-174960e746a1"),
                            ParamGroupId = 1,
                            ParamName = "Device1_CutO2Cut"
                        },
                        new
                        {
                            Id = new Guid("770b57fc-7663-4931-a36b-c0a1e9b7ba44"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("fdd9435b-5cfb-408b-bc08-8ba84cbf9aa2"),
                            ParamGroupId = 1,
                            ParamName = "Device1_IgnitionFlameAdjust"
                        },
                        new
                        {
                            Id = new Guid("e2f26639-2ad7-4c84-8160-3aa693afba91"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("d4808111-46b4-4310-a30b-2f0bc5e66bff"),
                            ParamGroupId = 3,
                            ParamName = "Device1_TactileInitialPosFinding"
                        },
                        new
                        {
                            Id = new Guid("a571ee11-5a2d-4ee9-bef5-fea23eb9ec3b"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("9e09daef-4a50-4d70-ae01-5aa3c8028b67"),
                            ParamGroupId = 3,
                            ParamName = "Device1_DistanceCalibration"
                        },
                        new
                        {
                            Id = new Guid("0d6cd1e1-a72e-408f-9373-84ea7fa3f50c"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("d9d65f61-b07a-45cb-b513-eeda945023da"),
                            ParamGroupId = 3,
                            ParamName = "Device1_Dynamic"
                        },
                        new
                        {
                            Id = new Guid("26c6a62e-6bc0-4398-a29a-0a520a7466ae"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("f02c2c84-8bd5-4b85-b137-4404b2031947"),
                            ParamGroupId = 9,
                            ParamName = "Device1_HeightControlActive"
                        },
                        new
                        {
                            Id = new Guid("6f8bf121-4cdc-463e-9788-b5ae55cdbbfd"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("de174409-1c4d-45e2-abe8-0d6c19dd9856"),
                            ParamGroupId = 8,
                            ParamName = "Device1_Off"
                        },
                        new
                        {
                            Id = new Guid("db631dd8-f32b-40ad-91d3-0d5c7ada6c5a"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("006d7287-6eac-416a-b736-98043f4c9c42"),
                            ParamGroupId = 8,
                            ParamName = "Device1_HeightPreHeat"
                        },
                        new
                        {
                            Id = new Guid("6c4cf865-74da-4bac-a0cc-65b827b8cbe0"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("67de7b28-2615-4e05-9a18-7d0709ed92cc"),
                            ParamGroupId = 8,
                            ParamName = "Device1_HeightPierce"
                        },
                        new
                        {
                            Id = new Guid("8aa82f03-a86c-4edd-b3b8-da47144ebbd0"),
                            APCDeviceId = new Guid("0e102fcc-cf3a-4047-9833-ba1c14bb01e6"),
                            DynParamsId = new Guid("9d3ecf58-222e-446b-addd-7c013ca96634"),
                            ParamGroupId = 8,
                            ParamName = "Device1_HeightCut"
                        },
                        new
                        {
                            Id = new Guid("9ba57194-23d0-48a1-ba7f-33d489e628e0"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("de94ded5-eab9-4ec7-bf24-cc75c4a07f81"),
                            ParamGroupId = 1,
                            ParamName = "Device2_HeatO2Ignition"
                        },
                        new
                        {
                            Id = new Guid("66ade3a4-1f75-40fc-82cc-1a2e503b40d4"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("72671a0c-f182-4ee7-973f-0971c2191086"),
                            ParamGroupId = 1,
                            ParamName = "Device2_HeatO2PreHeat"
                        },
                        new
                        {
                            Id = new Guid("e5fecc6e-018d-47d4-8da0-39d600dafb72"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("a2dcb6b8-963c-4823-b188-941a01f2bcac"),
                            ParamGroupId = 1,
                            ParamName = "Device2_HeatO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("075f4af0-5e8a-4286-8804-3cd136bf7ac7"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("d3e0f5ba-5f06-4b3e-b283-0b3047209fbc"),
                            ParamGroupId = 1,
                            ParamName = "Device2_HeatO2Cut"
                        },
                        new
                        {
                            Id = new Guid("e5ad7afd-dbfe-49fb-900e-0431560b1f4e"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("1773e2be-3151-4fb3-bfde-176e3ef750cb"),
                            ParamGroupId = 1,
                            ParamName = "Device2_FuelGasIgnition"
                        },
                        new
                        {
                            Id = new Guid("32795787-2d7a-4c5d-85eb-a657ccab8555"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("0aacca5b-bb83-4947-9571-947e2ef9f70f"),
                            ParamGroupId = 1,
                            ParamName = "Device2_FuelGasPreHeat"
                        },
                        new
                        {
                            Id = new Guid("6f5201e8-954d-4e2c-ab7b-93af95c40e9e"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("c8f8d3ef-b4cb-46f0-a5e5-d9b5e320b68c"),
                            ParamGroupId = 1,
                            ParamName = "Device2_FuelGasPierce"
                        },
                        new
                        {
                            Id = new Guid("aa9f2f8c-a8ab-4de7-a5a9-eef375b274cc"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("3bf5ea1a-4aeb-482a-8c8f-7aa4ffe0729b"),
                            ParamGroupId = 1,
                            ParamName = "Device2_FuelGasCut"
                        },
                        new
                        {
                            Id = new Guid("4a2b304e-3fe1-4911-8426-81535e3b3dd9"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("07431172-2134-443d-a786-371c02c93d62"),
                            ParamGroupId = 1,
                            ParamName = "Device2_CutO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("59cada09-a4db-48d1-9532-02a83247f019"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("bbd3cb20-577d-4e38-a80b-fb507e8e8d89"),
                            ParamGroupId = 1,
                            ParamName = "Device2_CutO2Cut"
                        },
                        new
                        {
                            Id = new Guid("c95cde9f-55a5-4a14-9561-f6a4b35687ce"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("af648d26-0fc5-4c1a-ba11-97520306c41e"),
                            ParamGroupId = 1,
                            ParamName = "Device2_IgnitionFlameAdjust"
                        },
                        new
                        {
                            Id = new Guid("04f109d6-354c-493a-a35d-8f77057168bb"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("98391455-cb1f-4284-8f19-c8ad4f7951ad"),
                            ParamGroupId = 3,
                            ParamName = "Device2_TactileInitialPosFinding"
                        },
                        new
                        {
                            Id = new Guid("d5db0bd6-00ff-4aaf-adae-ee37453ed271"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("37425a3a-0fcf-41af-8584-88eb5d720629"),
                            ParamGroupId = 3,
                            ParamName = "Device2_DistanceCalibration"
                        },
                        new
                        {
                            Id = new Guid("9d585e37-ebd5-4b07-be3a-dacab3d60d8a"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("ffb7793f-b0a4-450f-9f0b-419eab5e74d5"),
                            ParamGroupId = 3,
                            ParamName = "Device2_Dynamic"
                        },
                        new
                        {
                            Id = new Guid("0b8d3aa9-5eea-40a7-85c0-5760201c6cdc"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("96c95aee-c377-4c12-85d4-3fd61f94a16b"),
                            ParamGroupId = 9,
                            ParamName = "Device2_HeightControlActive"
                        },
                        new
                        {
                            Id = new Guid("b5334f8f-5f3d-4674-88b3-e49e40d4f5c1"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("05d06dd5-9c03-43e5-b9ac-c99baa414058"),
                            ParamGroupId = 8,
                            ParamName = "Device2_Off"
                        },
                        new
                        {
                            Id = new Guid("4a45e3b0-ad48-4fd6-ab38-fe3e84518111"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("65bde5c8-77e9-4166-b7b2-3029d2f2e866"),
                            ParamGroupId = 8,
                            ParamName = "Device2_HeightPreHeat"
                        },
                        new
                        {
                            Id = new Guid("cd7e4da6-e68c-4a7e-a799-5d6edfbed3e6"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("1687d4c8-c968-4177-a2f5-c98e375b2239"),
                            ParamGroupId = 8,
                            ParamName = "Device2_HeightPierce"
                        },
                        new
                        {
                            Id = new Guid("23d22d7b-fba0-4f8e-9371-2bd1ada4a5fe"),
                            APCDeviceId = new Guid("6b48ab2e-b156-49d9-bcb2-2ada69ce06f9"),
                            DynParamsId = new Guid("d6527850-1dca-4ac5-a220-0f4ef927c5fa"),
                            ParamGroupId = 8,
                            ParamName = "Device2_HeightCut"
                        },
                        new
                        {
                            Id = new Guid("29fa505b-c300-4ff1-b1e8-ebe4e12bc94b"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("3bb4d636-9373-4584-8a30-65b1f7044099"),
                            ParamGroupId = 1,
                            ParamName = "Device3_HeatO2Ignition"
                        },
                        new
                        {
                            Id = new Guid("5e5f3a7c-1c40-4082-ab44-0a102ea95f45"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("9bb7baeb-c1a9-42a8-b23d-fa8a7b641516"),
                            ParamGroupId = 1,
                            ParamName = "Device3_HeatO2PreHeat"
                        },
                        new
                        {
                            Id = new Guid("aac907ef-8e09-413f-a7b3-f3bd444c917a"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("8436b716-b197-469c-bdce-894173d336b0"),
                            ParamGroupId = 1,
                            ParamName = "Device3_HeatO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("63add317-49ae-4f0e-b00b-d4d2dc383666"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("722cfe71-d7fe-4721-bf37-169451617855"),
                            ParamGroupId = 1,
                            ParamName = "Device3_HeatO2Cut"
                        },
                        new
                        {
                            Id = new Guid("078cbefc-a938-4df9-aaa1-efde937738d4"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("90863bad-eda3-4320-858b-a8a84a5b0974"),
                            ParamGroupId = 1,
                            ParamName = "Device3_FuelGasIgnition"
                        },
                        new
                        {
                            Id = new Guid("76281600-0621-4f12-b540-df663a255593"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("b38d97c5-1a56-4448-a457-36ce9ae21539"),
                            ParamGroupId = 1,
                            ParamName = "Device3_FuelGasPreHeat"
                        },
                        new
                        {
                            Id = new Guid("0252b771-450e-48aa-9248-cc72c4a86c2a"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("1fcf6d0a-5651-4daa-9b13-5c8c4bf9d12b"),
                            ParamGroupId = 1,
                            ParamName = "Device3_FuelGasPierce"
                        },
                        new
                        {
                            Id = new Guid("9c5abf86-2f9e-4b11-b827-a21c4236a0f2"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("5b981638-4462-47f9-8390-8483fbb6a819"),
                            ParamGroupId = 1,
                            ParamName = "Device3_FuelGasCut"
                        },
                        new
                        {
                            Id = new Guid("b43c305d-1e7f-493c-b876-f41d661175dc"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("d3f5b3f0-097f-4652-8938-deeae91da1e9"),
                            ParamGroupId = 1,
                            ParamName = "Device3_CutO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("30d68784-5eea-4161-9e99-dd5193c62b3b"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("2b71293d-d4a6-4df0-88aa-5c7d02a2790a"),
                            ParamGroupId = 1,
                            ParamName = "Device3_CutO2Cut"
                        },
                        new
                        {
                            Id = new Guid("fbf73015-eeec-4bbb-a0f3-9fdf7d4af851"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("2f9c2b2b-3858-4523-b90e-248ea8a1db0d"),
                            ParamGroupId = 1,
                            ParamName = "Device3_IgnitionFlameAdjust"
                        },
                        new
                        {
                            Id = new Guid("d07b4a19-702a-47c7-a38c-110093a4c623"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("96cf84ad-6ec2-482a-b9c6-222b7f8ae1fe"),
                            ParamGroupId = 3,
                            ParamName = "Device3_TactileInitialPosFinding"
                        },
                        new
                        {
                            Id = new Guid("a636b597-82b6-4411-9b6e-facc1ec34add"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("44c772ad-22d2-4f02-a418-9b746766ed2a"),
                            ParamGroupId = 3,
                            ParamName = "Device3_DistanceCalibration"
                        },
                        new
                        {
                            Id = new Guid("0bd3de3c-958c-4168-a317-a6c435b2393c"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("84a52d5d-6719-4985-9631-32076e345a4c"),
                            ParamGroupId = 3,
                            ParamName = "Device3_Dynamic"
                        },
                        new
                        {
                            Id = new Guid("921b5c63-b279-4018-812d-c4732b233e81"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("8ee97e31-ef78-4aa8-b48a-9cb998b1bc14"),
                            ParamGroupId = 9,
                            ParamName = "Device3_HeightControlActive"
                        },
                        new
                        {
                            Id = new Guid("57a36bae-445a-4a92-8774-9463c02786f6"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("0736800c-d2aa-41d6-9c69-af21b1d666e1"),
                            ParamGroupId = 8,
                            ParamName = "Device3_Off"
                        },
                        new
                        {
                            Id = new Guid("f3933ce4-c55a-4a92-8e42-aea175feef17"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("63b78f1a-4831-4eaa-a2a2-e64540a3ae3b"),
                            ParamGroupId = 8,
                            ParamName = "Device3_HeightPreHeat"
                        },
                        new
                        {
                            Id = new Guid("d11dae75-8a02-4889-a477-c28b594fc571"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("f99b7a6e-25c9-40ae-87c2-af300228fc09"),
                            ParamGroupId = 8,
                            ParamName = "Device3_HeightPierce"
                        },
                        new
                        {
                            Id = new Guid("7be043a8-7d41-4acb-8da4-436227d038fe"),
                            APCDeviceId = new Guid("cec3f11a-59fc-4788-bb49-8585c94833cc"),
                            DynParamsId = new Guid("3095b08c-0fb9-4177-a511-77d842412710"),
                            ParamGroupId = 8,
                            ParamName = "Device3_HeightCut"
                        },
                        new
                        {
                            Id = new Guid("7f45a2ee-c104-49fc-9dd0-dd040b1e24b2"),
                            APCDeviceId = new Guid("77136ba4-8b3c-488d-b020-f8a8bdb396d2"),
                            DynParamsId = new Guid("6a91bddd-7720-4f5d-a677-a0eca0488814"),
                            ParamGroupId = 2,
                            ParamName = "System_RetractHeight"
                        },
                        new
                        {
                            Id = new Guid("1d1c4790-9646-41d8-97a5-8c1e94ae9881"),
                            APCDeviceId = new Guid("77136ba4-8b3c-488d-b020-f8a8bdb396d2"),
                            DynParamsId = new Guid("15b23a1b-0b77-4071-86fb-d95e96db1497"),
                            ParamGroupId = 9,
                            ParamName = "System_RetractPosition"
                        },
                        new
                        {
                            Id = new Guid("695ce38e-8a25-4ae2-8aea-5316e5c2b678"),
                            APCDeviceId = new Guid("77136ba4-8b3c-488d-b020-f8a8bdb396d2"),
                            DynParamsId = new Guid("7e1f090e-7366-42ba-a11d-d3853d97f7a5"),
                            ParamGroupId = 2,
                            ParamName = "System_SlagSensitivity"
                        },
                        new
                        {
                            Id = new Guid("41936b31-3fd4-4c84-bc7a-035a1a5038cb"),
                            APCDeviceId = new Guid("77136ba4-8b3c-488d-b020-f8a8bdb396d2"),
                            DynParamsId = new Guid("d1a5797b-f0ca-42bc-8af5-2ca52e25ff19"),
                            ParamGroupId = 2,
                            ParamName = "System_SlagPostTime"
                        },
                        new
                        {
                            Id = new Guid("b175e552-bb8f-4f9d-97d7-2b5c5d9e64c6"),
                            APCDeviceId = new Guid("77136ba4-8b3c-488d-b020-f8a8bdb396d2"),
                            DynParamsId = new Guid("fb9b52e0-54c4-4c15-aa64-e542bea25a75"),
                            ParamGroupId = 4,
                            ParamName = "System_SlagCuttingSpeedReduction"
                        },
                        new
                        {
                            Id = new Guid("96efa905-f198-45d7-b7ef-a333f36253d6"),
                            APCDeviceId = new Guid("77136ba4-8b3c-488d-b020-f8a8bdb396d2"),
                            DynParamsId = new Guid("e84acbad-2150-4f9e-8e7f-07ceb4e1b910"),
                            ParamGroupId = 9,
                            ParamName = "System_StartPreflow"
                        },
                        new
                        {
                            Id = new Guid("cacc2109-2429-4cd7-b005-c8532fd3c4b3"),
                            APCDeviceId = new Guid("77136ba4-8b3c-488d-b020-f8a8bdb396d2"),
                            DynParamsId = new Guid("59fc04e6-96fb-4156-a6a1-8e3445534945"),
                            ParamGroupId = 9,
                            ParamName = "System_PreflowActive"
                        },
                        new
                        {
                            Id = new Guid("ba7e58e7-9dac-427a-bbfc-d3400af0b39e"),
                            APCDeviceId = new Guid("77136ba4-8b3c-488d-b020-f8a8bdb396d2"),
                            DynParamsId = new Guid("32e1f3e0-b804-4c21-99f7-82f39c580417"),
                            ParamGroupId = 9,
                            ParamName = "System_PiercingHeightControl"
                        },
                        new
                        {
                            Id = new Guid("ba746216-b9cc-4175-90bf-7864cd77d5d4"),
                            APCDeviceId = new Guid("77136ba4-8b3c-488d-b020-f8a8bdb396d2"),
                            DynParamsId = new Guid("691230d6-86cb-4f1a-9ca9-affba7be70dd"),
                            ParamGroupId = 9,
                            ParamName = "System_PiercingDetection"
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.DynParams", b =>
                {
                    b.HasOne("BlazorServerHost.Data.Models.APCHardwareMock.ConstParams", "ConstParams")
                        .WithMany()
                        .HasForeignKey("ConstParamsId");

                    b.Navigation("ConstParams");
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.ParameterData", b =>
                {
                    b.HasOne("BlazorServerHost.Data.Models.APCHardwareMock.APCDevice", "APCDevice")
                        .WithMany()
                        .HasForeignKey("APCDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServerHost.Data.Models.APCHardwareMock.DynParams", "DynParams")
                        .WithMany()
                        .HasForeignKey("DynParamsId");

                    b.Navigation("APCDevice");

                    b.Navigation("DynParams");
                });
#pragma warning restore 612, 618
        }
    }
}
