// <auto-generated />
using System;
using BlazorServerHost.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServerHost.Data.Migrations.APCHardwareMock
{
    [DbContext(typeof(APCHardwareMockDBContext))]
    partial class APCHardwareMockDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.APCDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Num")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("APCDevices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            Name = "APCDevice_1",
                            Num = 1
                        },
                        new
                        {
                            Id = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            Name = "APCDevice_2",
                            Num = 2
                        },
                        new
                        {
                            Id = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            Name = "APCDevice_3",
                            Num = 3
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.ConstParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConstParams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22340841-bc7e-4a93-a5d9-17b75fae04c6"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("9e82b924-7963-4321-afee-e990ca31253b"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("62c9a576-40bf-419e-8359-b7d2f5d3408b"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("0855d37a-49a2-44e5-ba25-6742b562307b"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("6c050c73-e32e-435b-9606-65e6294eeb6d"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("a7e0e00a-bbab-45a5-a208-998b5a2e0d39"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("66581409-ff81-4fa8-a3ca-ea9445f86eba"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("ae2c1727-17eb-48a3-bd12-9e691982e335"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("4c31ddaa-a9b8-4e8c-bc74-5d0abe253d05"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("9e2082fa-4419-4ae6-8354-0abc74ea8a3c"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("ce456279-2e1a-47be-a93b-2507dc0ac374"),
                            Max = 1000,
                            Min = 200,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("ee9c5ae5-ccf4-4ecb-bc8a-edc6894fab73"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("4e8dbe95-60a1-42bb-b9ca-1f979e6b2d25"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("025fce1b-c0a9-4fd0-9353-f3796ea4707a"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("6d27ec27-5ee5-466d-ad95-38b2c5b6f819"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("9b946901-a377-488d-a894-6354a89c931b"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("249ad0f9-d2e4-4da4-981c-09e5fc33af91"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("abd0bada-3932-4292-aa19-c1fa8f0f9c2f"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("83811fd5-e9d0-4139-b039-a3a058a6f83e"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("2a7bc61e-44fe-4380-ac0f-056cc0aebd97"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("ca93f9d5-a401-44f4-bb5b-d8d492b61fb4"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("304495c1-fedd-467b-bed7-8378154bda87"),
                            Max = 1000,
                            Min = 200,
                            Step = 1
                        },
                        new
                        {
                            Id = new Guid("34e0f9f9-d353-4588-82c2-a5a2e6782aee"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("6372f193-7163-40bb-a1f3-eb974c69477d"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("1bbff2fd-de51-4941-8291-6dc12c3006ad"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("71f62801-e2da-4f50-acab-984e70109d49"),
                            Max = 5000,
                            Min = 500,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("8314b8e6-71f1-4f9a-a893-f671ab3d7b38"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("5086cb77-5121-4042-adb6-9171c0d584e4"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("9de6cb89-270b-4d1b-8834-475bb1eff1bc"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("e758f18b-3c3c-46e7-b2be-725a9c549ae1"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("d8626611-2945-414b-9d7b-f0ff915eb80e"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("df85dcd9-3e55-4e0b-97bc-585514535052"),
                            Max = 1000,
                            Min = 0,
                            Step = 10
                        },
                        new
                        {
                            Id = new Guid("411b507a-76c8-4158-a9c0-0405690d1947"),
                            Max = 1000,
                            Min = 200,
                            Step = 1
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.DynParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConstParamsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConstParamsId");

                    b.ToTable("DynParams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7420daab-942c-4522-bea8-55eef89d23a6"),
                            ConstParamsId = new Guid("22340841-bc7e-4a93-a5d9-17b75fae04c6"),
                            ParamId = 3,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("b2613df3-1c53-4f48-9c20-ecb9b5b8e203"),
                            ConstParamsId = new Guid("9e82b924-7963-4321-afee-e990ca31253b"),
                            ParamId = 4,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("6cc234ee-7ad4-4daa-9d93-50731f0bbd06"),
                            ConstParamsId = new Guid("62c9a576-40bf-419e-8359-b7d2f5d3408b"),
                            ParamId = 5,
                            Value = 4000
                        },
                        new
                        {
                            Id = new Guid("ac04fde6-761c-455a-a457-6037a9d9981a"),
                            ConstParamsId = new Guid("0855d37a-49a2-44e5-ba25-6742b562307b"),
                            ParamId = 6,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("a3ab3e61-28ee-4cf0-af50-593a97ab66bf"),
                            ConstParamsId = new Guid("6c050c73-e32e-435b-9606-65e6294eeb6d"),
                            ParamId = 9,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("b2174e27-f7ea-4fd4-9d12-6cca5d78aa84"),
                            ConstParamsId = new Guid("a7e0e00a-bbab-45a5-a208-998b5a2e0d39"),
                            ParamId = 10,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("b305ab5c-5664-4a21-9374-65a8fd2922a8"),
                            ConstParamsId = new Guid("66581409-ff81-4fa8-a3ca-ea9445f86eba"),
                            ParamId = 11,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("88399f09-01be-46c9-98ca-183e37811cd8"),
                            ConstParamsId = new Guid("ae2c1727-17eb-48a3-bd12-9e691982e335"),
                            ParamId = 12,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("e39ce774-3302-4556-8a3f-15e618abd035"),
                            ConstParamsId = new Guid("4c31ddaa-a9b8-4e8c-bc74-5d0abe253d05"),
                            ParamId = 7,
                            Value = 1500
                        },
                        new
                        {
                            Id = new Guid("26564483-4e87-44c5-aa1f-08c929b0933d"),
                            ConstParamsId = new Guid("9e2082fa-4419-4ae6-8354-0abc74ea8a3c"),
                            ParamId = 8,
                            Value = 6000
                        },
                        new
                        {
                            Id = new Guid("e5418611-29b0-41b4-ae77-f4e0ebc9a48c"),
                            ConstParamsId = new Guid("ce456279-2e1a-47be-a93b-2507dc0ac374"),
                            ParamId = 20,
                            Value = 500
                        },
                        new
                        {
                            Id = new Guid("fab75120-ef58-4c06-a022-8cc3aa4c0edb"),
                            ConstParamsId = new Guid("ee9c5ae5-ccf4-4ecb-bc8a-edc6894fab73"),
                            ParamId = 3,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("462fd30d-5998-45f9-8eb8-2f207df2b2e3"),
                            ConstParamsId = new Guid("4e8dbe95-60a1-42bb-b9ca-1f979e6b2d25"),
                            ParamId = 4,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("be9b7fc5-2cbe-4762-a740-759a56962c36"),
                            ConstParamsId = new Guid("025fce1b-c0a9-4fd0-9353-f3796ea4707a"),
                            ParamId = 5,
                            Value = 4000
                        },
                        new
                        {
                            Id = new Guid("61bdfaa0-f138-40bc-90e6-ad518b777f07"),
                            ConstParamsId = new Guid("6d27ec27-5ee5-466d-ad95-38b2c5b6f819"),
                            ParamId = 6,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("80cde3e1-534c-448e-bb93-3f725d5b7c35"),
                            ConstParamsId = new Guid("9b946901-a377-488d-a894-6354a89c931b"),
                            ParamId = 9,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("0e56b3ed-e8b1-470d-860b-0aa38676f186"),
                            ConstParamsId = new Guid("249ad0f9-d2e4-4da4-981c-09e5fc33af91"),
                            ParamId = 10,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("6c113bc4-9a13-4490-8151-f95bb0df0b42"),
                            ConstParamsId = new Guid("abd0bada-3932-4292-aa19-c1fa8f0f9c2f"),
                            ParamId = 11,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("1817805c-f9f7-476a-88d1-e762d0cf0b81"),
                            ConstParamsId = new Guid("83811fd5-e9d0-4139-b039-a3a058a6f83e"),
                            ParamId = 12,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("63c66b52-7ff9-4db3-9a75-86d60f72b655"),
                            ConstParamsId = new Guid("2a7bc61e-44fe-4380-ac0f-056cc0aebd97"),
                            ParamId = 7,
                            Value = 1500
                        },
                        new
                        {
                            Id = new Guid("e6465950-ffe5-466f-bc04-e13e5b2b595e"),
                            ConstParamsId = new Guid("ca93f9d5-a401-44f4-bb5b-d8d492b61fb4"),
                            ParamId = 8,
                            Value = 6000
                        },
                        new
                        {
                            Id = new Guid("1dd1edf9-c049-459d-9862-8acf3c73df9e"),
                            ConstParamsId = new Guid("304495c1-fedd-467b-bed7-8378154bda87"),
                            ParamId = 20,
                            Value = 500
                        },
                        new
                        {
                            Id = new Guid("5b2ca97a-0cf1-47a4-a3d5-32b3976e70c3"),
                            ConstParamsId = new Guid("34e0f9f9-d353-4588-82c2-a5a2e6782aee"),
                            ParamId = 3,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("391d0b37-3500-44fb-9e21-832078b6748d"),
                            ConstParamsId = new Guid("6372f193-7163-40bb-a1f3-eb974c69477d"),
                            ParamId = 4,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("d9aac3f7-2975-4921-9f5c-8445711543fa"),
                            ConstParamsId = new Guid("1bbff2fd-de51-4941-8291-6dc12c3006ad"),
                            ParamId = 5,
                            Value = 4000
                        },
                        new
                        {
                            Id = new Guid("ad90b0e9-3098-4836-8595-87ab734a839e"),
                            ConstParamsId = new Guid("71f62801-e2da-4f50-acab-984e70109d49"),
                            ParamId = 6,
                            Value = 2000
                        },
                        new
                        {
                            Id = new Guid("e1da9a7c-fa97-4ecd-8191-62b4bf63eea3"),
                            ConstParamsId = new Guid("8314b8e6-71f1-4f9a-a893-f671ab3d7b38"),
                            ParamId = 9,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("2e7fa486-65b4-410b-b378-241112bc436b"),
                            ConstParamsId = new Guid("5086cb77-5121-4042-adb6-9171c0d584e4"),
                            ParamId = 10,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("34413dde-b182-4562-a339-34d0674512b3"),
                            ConstParamsId = new Guid("9de6cb89-270b-4d1b-8834-475bb1eff1bc"),
                            ParamId = 11,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("57792d65-24d6-4b87-a926-7a15f837c442"),
                            ConstParamsId = new Guid("e758f18b-3c3c-46e7-b2be-725a9c549ae1"),
                            ParamId = 12,
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("6759bc3b-6e04-4c66-8dad-97557f85b0c0"),
                            ConstParamsId = new Guid("d8626611-2945-414b-9d7b-f0ff915eb80e"),
                            ParamId = 7,
                            Value = 1500
                        },
                        new
                        {
                            Id = new Guid("bc3782c5-9993-4dfb-93e0-d9e5fc03c462"),
                            ConstParamsId = new Guid("df85dcd9-3e55-4e0b-97bc-585514535052"),
                            ParamId = 8,
                            Value = 6000
                        },
                        new
                        {
                            Id = new Guid("4e347357-d5c8-42af-a531-6c24e64828cd"),
                            ConstParamsId = new Guid("411b507a-76c8-4158-a9c0-0405690d1947"),
                            ParamId = 20,
                            Value = 500
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.LiveParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LiveParams");
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.ParameterData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("APCDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DynParamsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("APCDeviceId");

                    b.HasIndex("DynParamsId");

                    b.ToTable("ParameterDatas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d651130c-cdca-4c7b-931b-31de1c286932"),
                            APCDeviceId = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            DynParamsId = new Guid("7420daab-942c-4522-bea8-55eef89d23a6"),
                            ParamName = "Device1_HeatO2Ignition"
                        },
                        new
                        {
                            Id = new Guid("5ae2cdf3-4034-4693-a514-60c7177f195f"),
                            APCDeviceId = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            DynParamsId = new Guid("b2613df3-1c53-4f48-9c20-ecb9b5b8e203"),
                            ParamName = "Device1_HeatO2PreHeat"
                        },
                        new
                        {
                            Id = new Guid("173d2275-0e36-40c8-85d8-eb40fe016c3a"),
                            APCDeviceId = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            DynParamsId = new Guid("6cc234ee-7ad4-4daa-9d93-50731f0bbd06"),
                            ParamName = "Device1_HeatO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("818ceb88-7229-4a79-a801-31afd7e2d136"),
                            APCDeviceId = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            DynParamsId = new Guid("ac04fde6-761c-455a-a457-6037a9d9981a"),
                            ParamName = "Device1_HeatO2Cut"
                        },
                        new
                        {
                            Id = new Guid("a470f116-cfc6-42ed-a71b-caf645a869bd"),
                            APCDeviceId = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            DynParamsId = new Guid("a3ab3e61-28ee-4cf0-af50-593a97ab66bf"),
                            ParamName = "Device1_FuelGasIgnition"
                        },
                        new
                        {
                            Id = new Guid("8b0a6717-79bb-422c-a3d6-203ef3bb9c01"),
                            APCDeviceId = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            DynParamsId = new Guid("b2174e27-f7ea-4fd4-9d12-6cca5d78aa84"),
                            ParamName = "Device1_FuelGasPreHeat"
                        },
                        new
                        {
                            Id = new Guid("36fe0036-c33a-4ce3-9afd-e73b7376d322"),
                            APCDeviceId = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            DynParamsId = new Guid("b305ab5c-5664-4a21-9374-65a8fd2922a8"),
                            ParamName = "Device1_FuelGasPierce"
                        },
                        new
                        {
                            Id = new Guid("56187ace-3589-4f13-9b51-6dc68ecd14d5"),
                            APCDeviceId = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            DynParamsId = new Guid("88399f09-01be-46c9-98ca-183e37811cd8"),
                            ParamName = "Device1_FuelGasCut"
                        },
                        new
                        {
                            Id = new Guid("94d58f57-e013-4968-83bb-2254900d26b0"),
                            APCDeviceId = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            DynParamsId = new Guid("e39ce774-3302-4556-8a3f-15e618abd035"),
                            ParamName = "Device1_CutO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("6084ecb0-c3e9-4f18-864b-40a755060074"),
                            APCDeviceId = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            DynParamsId = new Guid("26564483-4e87-44c5-aa1f-08c929b0933d"),
                            ParamName = "Device1_CutO2Cut"
                        },
                        new
                        {
                            Id = new Guid("09f6b35d-e08a-4421-9f5d-36631228cf8e"),
                            APCDeviceId = new Guid("5738f1cb-bf62-4884-9212-b758a1bbf68b"),
                            DynParamsId = new Guid("e5418611-29b0-41b4-ae77-f4e0ebc9a48c"),
                            ParamName = "Device1IgnitionFlameAdjust"
                        },
                        new
                        {
                            Id = new Guid("25f225f1-5621-46e1-b87a-c2d4d96bfbbe"),
                            APCDeviceId = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            DynParamsId = new Guid("fab75120-ef58-4c06-a022-8cc3aa4c0edb"),
                            ParamName = "Device2_HeatO2Ignition"
                        },
                        new
                        {
                            Id = new Guid("6bbf14bb-71a7-4e08-a49b-67e2469ead7c"),
                            APCDeviceId = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            DynParamsId = new Guid("462fd30d-5998-45f9-8eb8-2f207df2b2e3"),
                            ParamName = "Device2_HeatO2PreHeat"
                        },
                        new
                        {
                            Id = new Guid("92b65e8b-2da5-430c-a1ed-2e0a9ea95dab"),
                            APCDeviceId = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            DynParamsId = new Guid("be9b7fc5-2cbe-4762-a740-759a56962c36"),
                            ParamName = "Device2_HeatO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("169d9efe-8256-4fde-b061-405aa8a596cb"),
                            APCDeviceId = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            DynParamsId = new Guid("61bdfaa0-f138-40bc-90e6-ad518b777f07"),
                            ParamName = "Device2_HeatO2Cut"
                        },
                        new
                        {
                            Id = new Guid("ac8b24ca-7c10-4013-bb41-3847d32c4ac0"),
                            APCDeviceId = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            DynParamsId = new Guid("80cde3e1-534c-448e-bb93-3f725d5b7c35"),
                            ParamName = "Device2_FuelGasIgnition"
                        },
                        new
                        {
                            Id = new Guid("6977cfdd-0448-45e0-9d1a-db30b779d7ed"),
                            APCDeviceId = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            DynParamsId = new Guid("0e56b3ed-e8b1-470d-860b-0aa38676f186"),
                            ParamName = "Device2_FuelGasPreHeat"
                        },
                        new
                        {
                            Id = new Guid("2ff2a553-0ec6-428b-9605-4a0d4be99068"),
                            APCDeviceId = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            DynParamsId = new Guid("6c113bc4-9a13-4490-8151-f95bb0df0b42"),
                            ParamName = "Device2_FuelGasPierce"
                        },
                        new
                        {
                            Id = new Guid("eaa35fff-4d20-49a9-b2d4-9da9b0616f58"),
                            APCDeviceId = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            DynParamsId = new Guid("1817805c-f9f7-476a-88d1-e762d0cf0b81"),
                            ParamName = "Device2_FuelGasCut"
                        },
                        new
                        {
                            Id = new Guid("041475d0-9dc1-43a6-bf42-a793b86b4878"),
                            APCDeviceId = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            DynParamsId = new Guid("63c66b52-7ff9-4db3-9a75-86d60f72b655"),
                            ParamName = "Device2_CutO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("001d6f47-50c6-429c-806a-bf0be07e8579"),
                            APCDeviceId = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            DynParamsId = new Guid("e6465950-ffe5-466f-bc04-e13e5b2b595e"),
                            ParamName = "Device2_CutO2Cut"
                        },
                        new
                        {
                            Id = new Guid("1722d702-04f4-46c9-9f9b-8160c01c0bfd"),
                            APCDeviceId = new Guid("758a0f68-8677-4071-b8b8-c2919112fc23"),
                            DynParamsId = new Guid("1dd1edf9-c049-459d-9862-8acf3c73df9e"),
                            ParamName = "Device2IgnitionFlameAdjust"
                        },
                        new
                        {
                            Id = new Guid("485fcd84-bcd2-4214-96c9-7f547a640b21"),
                            APCDeviceId = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            DynParamsId = new Guid("5b2ca97a-0cf1-47a4-a3d5-32b3976e70c3"),
                            ParamName = "Device3_HeatO2Ignition"
                        },
                        new
                        {
                            Id = new Guid("c3ac0316-9b40-40a8-b65a-520b13092f59"),
                            APCDeviceId = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            DynParamsId = new Guid("391d0b37-3500-44fb-9e21-832078b6748d"),
                            ParamName = "Device3_HeatO2PreHeat"
                        },
                        new
                        {
                            Id = new Guid("e499612e-4d9d-42f9-96ac-7ec14f067cd9"),
                            APCDeviceId = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            DynParamsId = new Guid("d9aac3f7-2975-4921-9f5c-8445711543fa"),
                            ParamName = "Device3_HeatO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("74f34648-3f2e-4fa7-b53a-6745e4bf452f"),
                            APCDeviceId = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            DynParamsId = new Guid("ad90b0e9-3098-4836-8595-87ab734a839e"),
                            ParamName = "Device3_HeatO2Cut"
                        },
                        new
                        {
                            Id = new Guid("f3ced4de-2214-4fd8-88d4-7de7b9060c22"),
                            APCDeviceId = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            DynParamsId = new Guid("e1da9a7c-fa97-4ecd-8191-62b4bf63eea3"),
                            ParamName = "Device3_FuelGasIgnition"
                        },
                        new
                        {
                            Id = new Guid("2649d3dd-be59-429a-8c4a-ec81bc42948e"),
                            APCDeviceId = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            DynParamsId = new Guid("2e7fa486-65b4-410b-b378-241112bc436b"),
                            ParamName = "Device3_FuelGasPreHeat"
                        },
                        new
                        {
                            Id = new Guid("beb4f00d-5bac-47fb-80f7-470b312a258f"),
                            APCDeviceId = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            DynParamsId = new Guid("34413dde-b182-4562-a339-34d0674512b3"),
                            ParamName = "Device3_FuelGasPierce"
                        },
                        new
                        {
                            Id = new Guid("d0101f02-5ff4-4f1d-b473-2a55d6980292"),
                            APCDeviceId = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            DynParamsId = new Guid("57792d65-24d6-4b87-a926-7a15f837c442"),
                            ParamName = "Device3_FuelGasCut"
                        },
                        new
                        {
                            Id = new Guid("c537a104-d9a1-4a9e-a302-4541d75d4a09"),
                            APCDeviceId = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            DynParamsId = new Guid("6759bc3b-6e04-4c66-8dad-97557f85b0c0"),
                            ParamName = "Device3_CutO2Pierce"
                        },
                        new
                        {
                            Id = new Guid("aa119ea0-d1ec-4bdf-9244-479080422350"),
                            APCDeviceId = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            DynParamsId = new Guid("bc3782c5-9993-4dfb-93e0-d9e5fc03c462"),
                            ParamName = "Device3_CutO2Cut"
                        },
                        new
                        {
                            Id = new Guid("d3951ceb-2b79-44c4-9817-a01c1f09fc20"),
                            APCDeviceId = new Guid("590f87c6-f007-43e6-a9dd-cd8c674f86dd"),
                            DynParamsId = new Guid("4e347357-d5c8-42af-a531-6c24e64828cd"),
                            ParamName = "Device3IgnitionFlameAdjust"
                        });
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.DynParams", b =>
                {
                    b.HasOne("BlazorServerHost.Data.Models.APCHardwareMock.ConstParams", "ConstParams")
                        .WithMany()
                        .HasForeignKey("ConstParamsId");

                    b.Navigation("ConstParams");
                });

            modelBuilder.Entity("BlazorServerHost.Data.Models.APCHardwareMock.ParameterData", b =>
                {
                    b.HasOne("BlazorServerHost.Data.Models.APCHardwareMock.APCDevice", "APCDevice")
                        .WithMany()
                        .HasForeignKey("APCDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServerHost.Data.Models.APCHardwareMock.DynParams", "DynParams")
                        .WithMany()
                        .HasForeignKey("DynParamsId");

                    b.Navigation("APCDevice");

                    b.Navigation("DynParams");
                });
#pragma warning restore 612, 618
        }
    }
}
