// <auto-generated />
using System;
using IhtApcWebServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IhtApcWebServer.Data.Migrations.CuttingData
{
    [DbContext(typeof(CuttingDataDbContext))]
    [Migration("20221114164530_Create_Schema_AndSeed")]
    partial class Create_Schema_AndSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("IhtApcWebServer.Data.Models.CuttingData.APCCuttingParametersIHT", b =>
                {
                    b.Property<int>("ControlBits")
                        .HasColumnType("INTEGER");

                    b.Property<float>("CutCuttingOxygenPressure")
                        .HasColumnType("REAL");

                    b.Property<float>("CutFuelGasPressure")
                        .HasColumnType("REAL");

                    b.Property<float>("CutHeatingOxygenPressure")
                        .HasColumnType("REAL");

                    b.Property<int>("CutHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuttingSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("IgnitionFlameAdjustment")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Kerf")
                        .HasColumnType("REAL");

                    b.Property<int>("LeadInLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nozzle")
                        .HasColumnType("TEXT");

                    b.Property<float>("PI0")
                        .HasColumnType("REAL");

                    b.Property<float>("PI1")
                        .HasColumnType("REAL");

                    b.Property<int>("PP0")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PP1")
                        .HasColumnType("REAL");

                    b.Property<float>("PP2")
                        .HasColumnType("REAL");

                    b.Property<float>("PP3")
                        .HasColumnType("REAL");

                    b.Property<float>("PP4")
                        .HasColumnType("REAL");

                    b.Property<float>("PierceCuttingOxygenPressure")
                        .HasColumnType("REAL");

                    b.Property<int>("PierceCuttingSpeedChange")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PierceFuelGasPressure")
                        .HasColumnType("REAL");

                    b.Property<float>("PierceHeatingOxygenPressure")
                        .HasColumnType("REAL");

                    b.Property<int>("PierceHeight")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PierceTime")
                        .HasColumnType("REAL");

                    b.Property<float>("PreHeatFuelGasPressure")
                        .HasColumnType("REAL");

                    b.Property<float>("PreHeatHeatingOxygenPressure")
                        .HasColumnType("REAL");

                    b.Property<int>("PreHeatHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreHeatTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<int>("Thickness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idGas")
                        .HasColumnType("INTEGER");

                    b.ToTable("APCCuttingParametersIHT");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.CuttingData.CustomCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CounterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CustomCounter");

                    b.HasData(
                        new
                        {
                            Id = new Guid("144b41f7-64d1-4d28-a1b9-4aed7f94a6b9"),
                            CounterId = 1
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.CuttingData.CuttingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Controlbits")
                        .HasColumnType("INTEGER");

                    b.Property<float>("CutCuttingOxygenPressure")
                        .HasColumnType("REAL");

                    b.Property<float>("CutFuelGasPressure")
                        .HasColumnType("REAL");

                    b.Property<float>("CutHeatingOxygenPressure")
                        .HasColumnType("REAL");

                    b.Property<int>("CutHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuttingSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GasId")
                        .HasColumnType("TEXT");

                    b.Property<int>("IgnitionFlameAdjustment")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Kerf")
                        .HasColumnType("REAL");

                    b.Property<int>("LeadInLength")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NozzleId")
                        .HasColumnType("TEXT");

                    b.Property<float>("PI0")
                        .HasColumnType("REAL");

                    b.Property<float>("PI1")
                        .HasColumnType("REAL");

                    b.Property<float>("PP0")
                        .HasColumnType("REAL");

                    b.Property<float>("PP1")
                        .HasColumnType("REAL");

                    b.Property<float>("PP2")
                        .HasColumnType("REAL");

                    b.Property<float>("PP3")
                        .HasColumnType("REAL");

                    b.Property<float>("PP4")
                        .HasColumnType("REAL");

                    b.Property<float>("PierceCuttingOxygenPressure")
                        .HasColumnType("REAL");

                    b.Property<int>("PierceCuttingSpeedChange")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PierceFuelGasPressure")
                        .HasColumnType("REAL");

                    b.Property<float>("PierceHeatingOxygenPressure")
                        .HasColumnType("REAL");

                    b.Property<int>("PierceHeight")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PierceTime")
                        .HasColumnType("REAL");

                    b.Property<float>("PreHeatFuelGasPressure")
                        .HasColumnType("REAL");

                    b.Property<float>("PreHeatHeatingOxygenPressure")
                        .HasColumnType("REAL");

                    b.Property<int>("PreHeatHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreHeatTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<float>("Thickness")
                        .HasColumnType("REAL");

                    b.Property<int?>("idCutDataParent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GasId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("NozzleId");

                    b.ToTable("CuttingData");
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.CuttingData.Gas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("GasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2640602-8975-4ba9-a77a-d39d9adf569f"),
                            GasId = 0,
                            Name = "Propan"
                        },
                        new
                        {
                            Id = new Guid("f4a41b2c-6af0-4831-bc6f-e1413a43d4c9"),
                            GasId = 1,
                            Name = "Acetylene"
                        },
                        new
                        {
                            Id = new Guid("0612c322-c0c2-46ad-b832-b1a54988be2a"),
                            GasId = 2,
                            Name = "NaturalGas"
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.CuttingData.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Material");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c2ad9a1-9c3e-4932-a3bd-17eb93ad0c09"),
                            Name = "Mild Steel"
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.CuttingData.Nozzle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgPathBegin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgPathEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nozzle");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c84b055a-b876-4d30-ae51-fdba16594078"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "ARC 3-40"
                        },
                        new
                        {
                            Id = new Guid("4963a699-1abd-415b-8a9c-c711985f42d7"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "ARC 3-70"
                        },
                        new
                        {
                            Id = new Guid("de04c785-83f7-421b-89eb-13be7897204d"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PRC 5-40"
                        },
                        new
                        {
                            Id = new Guid("b4fb431e-faa6-4614-a36d-b1265b60aadd"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PRC 5-70"
                        },
                        new
                        {
                            Id = new Guid("2d9e20a1-0151-47fd-9ecb-6a107fb03b41"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "ASF 3-5"
                        },
                        new
                        {
                            Id = new Guid("1475e10e-4363-45ca-a06b-0da0f38f622c"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "ASF 6-10"
                        },
                        new
                        {
                            Id = new Guid("436e048e-7fd8-4704-b2db-70749fd70393"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "ASF 10-25"
                        },
                        new
                        {
                            Id = new Guid("167ba134-cfff-4d24-a5bb-333d7209b4a4"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "ASF 25-40"
                        },
                        new
                        {
                            Id = new Guid("53106f95-084f-45a5-80a1-16e9934ce44a"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "ASF 40-60"
                        },
                        new
                        {
                            Id = new Guid("b86c11e1-b53f-4980-9c31-c6ec3b2b0f5a"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "ASF 60-100"
                        },
                        new
                        {
                            Id = new Guid("7dd82824-986d-4ee1-bc1a-5523572efe70"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "ASF 100-150"
                        },
                        new
                        {
                            Id = new Guid("2d70f786-db08-48e2-9934-e9827e05e913"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "ASF 150-230"
                        },
                        new
                        {
                            Id = new Guid("45bf6661-0e40-4be1-9448-1372ebfbb59e"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "ASF 230-300"
                        },
                        new
                        {
                            Id = new Guid("dfad8b3c-79c2-4512-87d4-1be600baf665"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PSF 3-6"
                        },
                        new
                        {
                            Id = new Guid("465889f7-a1dc-4a54-93e9-7ce7b7e26ca8"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PSF 7-15"
                        },
                        new
                        {
                            Id = new Guid("c34094ae-c9e5-446a-90ba-424eded2325b"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PSF 15-25"
                        },
                        new
                        {
                            Id = new Guid("0f565018-afd1-41ae-95e0-32708df00dd1"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PSF 25-40"
                        },
                        new
                        {
                            Id = new Guid("ebcdcf9f-e4cf-413f-a671-c1382ebd64f9"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PSF 40-60"
                        },
                        new
                        {
                            Id = new Guid("2c1b57ed-8eb2-48db-aead-e6704e05b007"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PSF 60-100"
                        },
                        new
                        {
                            Id = new Guid("ddb4881e-9843-4f30-8479-f5df99f865d5"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PSF 100-150"
                        },
                        new
                        {
                            Id = new Guid("78b18562-694e-46b4-a24c-a601d3a5c773"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PSF 100-200"
                        },
                        new
                        {
                            Id = new Guid("d810c12b-69d1-45a4-9817-ad39679f4dd0"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PSF 150-200"
                        },
                        new
                        {
                            Id = new Guid("45926932-9fa5-4639-a043-9764aa7d062b"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PSF 200-250"
                        },
                        new
                        {
                            Id = new Guid("3c995426-49cb-457f-a9f5-7ab3a8234e5e"),
                            ImgPathBegin = "",
                            ImgPathEnd = "",
                            Name = "PSF 250-300"
                        });
                });

            modelBuilder.Entity("IhtApcWebServer.Data.Models.CuttingData.CuttingData", b =>
                {
                    b.HasOne("IhtApcWebServer.Data.Models.CuttingData.Gas", "Gas")
                        .WithMany()
                        .HasForeignKey("GasId");

                    b.HasOne("IhtApcWebServer.Data.Models.CuttingData.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.HasOne("IhtApcWebServer.Data.Models.CuttingData.Nozzle", "Nozzle")
                        .WithMany()
                        .HasForeignKey("NozzleId");

                    b.Navigation("Gas");

                    b.Navigation("Material");

                    b.Navigation("Nozzle");
                });
#pragma warning restore 612, 618
        }
    }
}
